### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by pheim1** [gedankenessen/goose-frontend#102]
**Beschreibung des Bugs**
Ein sehr kleiner Bug, aber dennoch ein Bug 🧐

**Reproduktions Schritte**
Frontend via [http://ticketgoose.de/](http://ticketgoose.de/) öffnen.

**Erwartetes Verhalten**
Ich erhalten einen weißen Bildschirm, möchte aber zumindest das Login-View als default Fallback. (Optional) Hätte ich jedoch einen noch nicht abgelaufenen Token im localstorage, so möchte ich mich nicht nochmal anmelden und vllt auf das Dashboard weitergeleitet werden.

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
Fixed und in main
