### ISSUE TITLE
Nach dem Registrieren wird die Company nicht im LocalStorage gespeichert

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-frontend#105]
**Beschreibung des Bugs**
Hey, im Moment wird nach dem Registrieren die Company noch nicht im Local Storage gespeichert.

**Reproduktions Schritte**
1. Neue Firma erstellen unter '/register'
2. LocalStorage einsehen (Application -> Local Storage)

**Erwartetes Verhalten**
Company wird nach dem Registrieren auch im Local Storage gespeichert

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
#110
