### ISSUE TITLE
Ticket kann Deadline vor Startdatum sein

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#106]
Fehler tritt auch mit der "nicht zusammengefassten" Version auf 😉 

**Ich schreibe das Issue das der Fehler vermerkt ist, es werden andere Bugs noch kommen die vor heute Abend gefixed werden müssen.**

Erstellen:
![Screen Shot 2021-05-06 at 10 58 02](https://user-images.githubusercontent.com/24259317/117271560-98df6900-ae5a-11eb-93dd-60132e52e028.png)

Bearbeiten: 
![Screen Shot 2021-05-06 at 11 02 03](https://user-images.githubusercontent.com/24259317/117271557-9846d280-ae5a-11eb-8893-199eba4f00b4.png)

**Branches**
- Frontend: demo_Plenarsitzung
- Backend: master

**Comment by BenjaminKuerten** [comment]
Der Fehler erscheint bei klick auf Speichern, es gibt verschiedene Meldungen
