### ISSUE TITLE
Bei erstellen von Issue wird Status zu beginn nicht richtig gesetzt

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#107]
https://user-images.githubusercontent.com/24259317/117272292-59654c80-ae5b-11eb-8c85-29fe9f3d0b45.mov

**Branches**
- Frontend: demo_Plenarsitzung
- Backend: master

**Comment by BenjaminKuerten** [comment]
Gerade mit einer frisch geklonten Main probiert 

https://user-images.githubusercontent.com/48795982/117317597-f048fd80-ae89-11eb-98cb-9b034a7a619b.mp4

**Comment by marlonschlosshauer** [comment]
Demo ist stand

**Comment by marlonschlosshauer** [comment]
Wähle mal "Feature" als aller erstes aus

**Comment by BenjaminKuerten** [comment]
Wie ist das möglich.... Angular ist manchmal....

**Comment by marlonschlosshauer** [comment]
👏 Template👏 Driven👏 Forms👏

**Comment by BenjaminKuerten** [comment]
#109 #108
