### ISSUE TITLE
Darktheme

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#111]
https://ng.ant.design/docs/customize-theme/en

**Comment by marlonschlosshauer** [comment]
@Namo2 Hast du es dir gestern nochmal angeschaut? Hätte das gerne bis Mittwoch (12.05).

**Comment by Namo2** [comment]
Hab mir das alles mal angeschaut. Im grunde könnten wir das Theoretisch implementieren. Ich denke aber nicht, dass sich das lohnen würde, da wir sehr viele hintergründe vordefiniert haben und das alles ändern müssten.
Zudem müssten wir laut `https://ng.ant.design/docs/customize-theme/en` in jeder der less dateien einen mixinwrapper einfügen.

Es würde noch einen anderen Ansatz geben wo wir aus zwei vordefinierten Themes css Dateien generieren die wir dann wechseln könnten. Allerdings gibt es dort nur das Compact und das Dark Theme was ein paar Probleme mit sich zieht. Zudem haben wir auch hier das Problem mit den vordefinierten Farben in einigen Komponenten.

**Comment by Namo2** [comment]
Falls wir uns nochmal an den Darkmode probieren wollen, ist hier der Link für Variante 2 als Referenz

https://github.com/AshotAleqs/ng-zorro-switch-theme
