### ISSUE TITLE
Sidebar aus App-Component aushebeln

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#112]
Das die Sidebar ``CompanyId`` und ``ProjectId`` benötigt macht Probleme. Sidebar ist in der App-Component greift also auf den gleichen ``ngOnInit`` zu. Zu dem Zeitpunkt hat sich der Nutzer aber noch nicht eingelogt. 

Hab keine Konkrete Implementation im Kopf, aber als wir drüber gesprochen haben hattest du den gleichen Ansatz: Sidebar in eigene Komponente. Über das Routing immer die Sidebar und die eigentliche Komponente (z.B. IssueDashboard) anzeigen.

**Deadline:** ca. Mittwoch vor Meeting (12.05)

**Comment by BenjaminKuerten** [comment]
Ich habe eine Idee im Kopf. Ich werde mich heute Abend oder morgen mal dran setzen.

**Comment by BenjaminKuerten** [comment]
Fix via #124
