### ISSUE TITLE
IssueDashboard: Card Design

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#115]
Zeplin: [Card-Design](https://zpl.io/2GXM3W4)

- Alles außer: Zeiterfassungs-Button
- Im Mockup kann man über ein "x" die Requirements entfernen. Ich glaube das sollte eher ein ✔️ sein, in dem man die Requirements als abgeschlossen melden kann (funktionalität gibt es dafür noch nicht) 
- Kannst auch nur die Requirements auflisten, eine "Checkbox" wäre nice-to-have

**Deadline:** Freitag (14.5), kleine Demo bis Mittwoch wäre cool

**Comment by sfuerder** [comment]
@marlonschlosshauer 2 Fragen:
1. Muss ich die gebuchte Zeit pro ticket selbst zusammen rechnen oder wird das irgendwo schon als summe gespeichert?
2. Ab wann können requirements abgehackt werde. Sobald requirementsAccepted auf true steht oder der Status auf Bearbeiten ist?

**Comment by sfuerder** [comment]
Ich habe gerade, um meinen teil weiter zu entwickeln kleiner Dinge an der Issue Dashboard Component ändern müssen. Macht es evtl Sinn mal einen Zwischenstand von @mschwer1 und mir zusammen zu mergen, damit man keine Funktionen doppelt entwickeln muss. Denke auch, dass es einiges an mergekonflikte geben könnte

**Comment by marlonschlosshauer** [comment]
>  Macht es evtl Sinn mal einen Zwischenstand von @mschwer1 und mir zusammen zu mergen

Ja gerne. Regelt das unter euch wie ihr am besten arbeitet.

**Comment by sfuerder** [comment]
Sollte sich gemerkt werden, welche Ansicht (Table oder Card)  als letztes ausgewählt wurde? Also dass man automatisch die zuletzt gewählte Ansicht zu sehen bekommt?

**Comment by marlonschlosshauer** [comment]
Gerne. Speicher ein Flag im localStorage und frag es beim laden von Dashboard Component (oder die Parent Component, falls es jetzt da eine gibt) ab.
