### ISSUE TITLE
IssueSettings: X darf Y und Verhalten

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#116]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T20 Nur Mitarbeiter sehen "Visibility" Auswahl bei Ticket Erstellen
- [x] T32 Auf Ticketansicht kann nur Projektleiter Status von Review zu Abschlussphase ändern (außer Abbruch Kunden)
- [x] T33 Auf Ticketansicht kann nur Projektleiter den Status "Archiviert" geben
- [x] T41 Auf Ticketansicht kann ein lesender Mitarbeiter nicht den Status ändern
- [x] T72 Auf Ticketeinstellungen können manche Eigenschaften (anhand von Phase) bearbeitet werden (siehe Ph.)
- [x] T93 Auf Ticketeinstellungen kann Status "Review" nur von Projektleiter verlassen werden 

Sollte beim Status eine Logik rein das man z.B. nicht selber auf Wartend gehen kann (normalerweise solange bis Startdatum nicht erreicht wurde, wird vom Backend zurückgesetzt) ?

**Deadline:** Freitag nächste Woche (14.05). Haltest du das für machbar oder zieht da #112 zu viel Zeit?

**Comment by BenjaminKuerten** [comment]
@marlonschlosshauer 
"Sollte beim Status eine Logik rein das man z.B. nicht selber auf Wartend gehen kann (normalerweise solange bis Startdatum nicht erreicht wurde, wird vom Backend zurückgesetzt) ?"

Sicherer wäre es über das Backend, aber das stellt keine Funktion dafür (zumindest mir nicht bekannt).

=> Ich würde es auf der Frontend-Seite einbauen

**Comment by marlonschlosshauer** [comment]
> => Ich würde es auf der Frontend-Seite einbauen

Yo bitte. 

> Sicherer wäre es über das Backend, aber das stellt keine Funktion dafür (zumindest mir nicht bekannt).

Das Backend würde (wird?) in der Zukunft einen PUT/POST ablehnen, der das versucht 👍

**Comment by BenjaminKuerten** [comment]
T72 bzw. F28 -> Aufwand wird nicht in den Ticketeinstellungen gesetzt

**Comment by marlonschlosshauer** [comment]
> T72 bzw. F28 -> Aufwand wird nicht in den Ticketeinstellungen gesetzt

Also ich hab es so verstanden das wenn die Verhandlungsphase geskipped wird, das man es in den Einstellungen eingeben kann.

**Comment by marlonschlosshauer** [comment]
Yoyo, meinst das ist bis Mittwoch ready?

**Comment by BenjaminKuerten** [comment]
Bekomme ich bis Mittwoch hin

**Comment by marlonschlosshauer** [comment]
Das is Live, ne?

**Comment by BenjaminKuerten** [comment]
Ja, #129 & #138

**Comment by marlonschlosshauer** [comment]
Lit 🔥
