### ISSUE TITLE
IssueTimesheet: UI + Funktionalität

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#117]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T25 Zeiterfassungen werden in Ticketansicht unter "Zeiten" angezeigt (siehe Pflichtenheft)
- [x] T30 Auf Zeitenansicht kann Projektleiter alle Zeiten ändern
- [x] T44 Auf Ticketansicht unter "Zeiten" werden alle Zeiten angezeigt
- [x] T45 Auf Ticketansicht unter "Zeiten" können Zeiten geändert werden

Außerdem würde dazu kommen das nur der Projektleiter Zeiten von anderen Ändern kann, aber das wäre ein nice-to-have. 

**Deadline**: Basis Funktionen bis Mittwoch (Demo am Freitag), Rest bis Freitag (oder falls zu viel bis Montag). Meinst das geht?

**Comment by Namo2** [comment]
> **Deadline**: Basis Funktionen bis Mittwoch (Demo am Freitag), Rest bis Freitag (oder falls zu viel bis Montag). Meinst das geht?

Sollte klargehen :+1:
