### ISSUE TITLE
IssueConversation: Letzte Touches + UI

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#118]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T19 Auf Ticketansicht nur Projektleiter sieht Zusammenfassung senden Button
- [x] T39 Auf Ticketansicht sieht ein lesender Mitarbeiter kein Nachrichtschreiben Feld und Senden Button
- [x] UI Redesign

Wenn du möchtest kannst das UI noch auffrischen. Statusänderungen aussehen lassen wie bei [Github](https://user-images.githubusercontent.com/24259317/117548737-ec0e1300-b036-11eb-950c-d30c0d690974.png). 

Ist etwas Ekelhaft wenn alles in einer Komponente ist. Wenn du merkst das es zu nervig wird kannst du dir ruhig die Zeit nehmen und alle in einzelne Komponenten zu verwandeln (mit Inputs & Outputs). 

**Deadline**: Zumindest die Tasks bis Mittwoch (12.05), Redesign bis Freitag (14.05) aber ist auch eigentlich egal.

**Comment by WhiroWhat** [comment]
Ich würde bei T19 und T39 eher deaktivieren statt ausblenden. Fände ich schöner.

**Comment by WhiroWhat** [comment]
T19 ->und Firma?

**Comment by marlonschlosshauer** [comment]
> Ich würde bei T19 und T39 eher deaktivieren statt ausblenden. Fände ich schöner.

Yo das wäre premium.

> T19 ->und Firma?

Yo die auch 👍
