### ISSUE TITLE
Logout Bug

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-frontend#119]
**Beschreibung des Bugs**
Beim verwenden des Logout-Buttons gibt es beim nächsten anmelden einen Fehler.

**Reproduktions Schritte**
1. Einloggen mit Daten
2. Logout-Button drücken
3. Neu anmelden
4. Error
![1](https://user-images.githubusercontent.com/48799541/117557049-77a39600-b06f-11eb-8217-3dc78737d406.PNG)
![2](https://user-images.githubusercontent.com/48799541/117557051-78d4c300-b06f-11eb-8dea-1a7456f28920.PNG)
![3](https://user-images.githubusercontent.com/48799541/117557053-7a9e8680-b06f-11eb-95f6-65ac6486ed15.PNG)
![4](https://user-images.githubusercontent.com/48799541/117557056-7c684a00-b06f-11eb-87a1-ad7e69f6a761.PNG)

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
@WhiroWhat lässt sich bei mir nicht reproduzieren

**Comment by WhiroWhat** [comment]
Hab es gerade nochmal probiert und ich kann ihn auch nicht reproduzieren.

**Comment by WhiroWhat** [comment]
fixed i guess
