### ISSUE TITLE
Priorität ist 0

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-frontend#121]
**Beschreibung des Bugs**
Wenn man ein Ticket anlegt, kann es passieren, dass die Priorität 0 genommen wird.

**Reproduktions Schritte**
1. Neues Ticket anlegen
2. Prioritätsregler nicht ändern
3. Ticket Speichern
4. Priorität ist 0

**Erwartetes Verhalten**
Normalerweise sollte die Priorität dann 1 sein. 
Wenn man den Regler auf 2 schiebt und dann wieder zurück auf 1 stimmt es.

**Branches**
- Frontend: feature/IssueCardDesign
- Backend: master

**Comment by BenjaminKuerten** [comment]
Fix via #125
