### ISSUE TITLE
Login Error Meldung

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-frontend#126]
Für Login wäre eine Error Meldung evtl. nicht schlecht (bei falschen Anmeldedaten)

**Comment by marlonschlosshauer** [comment]
Ich würde eine Error Meldung bevorzugen. 
![image](https://user-images.githubusercontent.com/24259317/118004247-93e25400-b349-11eb-827e-b90992024047.png)

Gibt bei den Forms auch die Möglichkeit da welche über ngError anzuzeigen.

**Comment by WhiroWhat** [comment]
jo das wäre vielleicht besser

**Comment by marlonschlosshauer** [comment]
bro geh schlafen was??
