### ISSUE TITLE
Card-Design: Requirements Abhaken

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#130]
Philipp ist da gerade im Backend dran. Sollte bis zum Ende der Woche für dich zur Verfügung stehen.

- [x] Requirements können abgehakt/angehakt werden
- [x] Nur Mitarbeiter mit Schreiberecht, Firma oder Projektleiter können das

**Comment by marlonschlosshauer** [comment]
Hey hey, das hat mittlerweile schon funktioniert, oder?

**Comment by sfuerder** [comment]
Ja. PR kommt gleich
