### ISSUE TITLE
Issue: Untertickets anzeigen, verlinken, erstellen (?)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#131]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T100 Auf Ticketansicht werden schon bestehende Untertickets angezeigt
- [x] T97 Auf Ticketansicht kann ein Unterticket erstellt werden (verweiß auf IssueSettings)
- [x] T101 Auf Ticketerstellung kann Unterticket weder in Abschlussphase noch in Review Status hinzugefügt werden

Benny Territorium:
- [x] T98 Auf Ticketseite bei erstellen von Unterticket benötigt man (fast) selbe Angaben wie Oberticket
- [x] T102 Auf Ticketerstellung bei erstellen von Unterticktes werden manche Werte vererbt (siehe Ph.)
- [x] T103 Auf Ticketerstellung bei erstellen von Unterticket ist Verhandlung automatisch ausgeschalten

**Comment by sfuerder** [comment]
@BenjaminKuerten wie schaut es mit T101-T103 aus? Kann gerne diese Funktionalität implementieren oder möchtest du das machen?

**Comment by BenjaminKuerten** [comment]
@sfuerder Können wir gerne zusammen machen oder du kannst es übernehmen. Können ja heute Abend oder morgen nach dem Meeting nochmal drüber sprechen.

**Comment by sfuerder** [comment]
Okay. Nach dem Meeting passt bei mir heute 👍🏼

**Comment by marlonschlosshauer** [comment]
Hey hey, hab leider einen Fehler mit den Aufgaben gemacht. Hab eins noch hinzugefügt. 
Ich würde T98, 102, 103 Benny geben weil Sebastian laut Tracebility einige Aufgaben hat. Habt ihr euch da auf was geeinigt?

**Comment by marlonschlosshauer** [comment]
Äh, wird ne knappe Lieferung?

**Comment by BenjaminKuerten** [comment]
@marlonschlosshauer, ja arbeite dran

**Comment by marlonschlosshauer** [comment]
#174 würde das hier schließen, oder?
