### ISSUE TITLE
IssueDashboard: Zeiterfassung

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#133]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T22 Auf Ticketdashboard kann Zeiterfassung gestartet/gestopt werden
- [x] T23 Nur Mitarbeiter kann auf Ticketdashboard Zeiterfassung starten/stoppen
- [x] T24 Auf Ticketdashboard nach Start von Zeiterfassung ändert Icon zu "Pause"
- [x] T40 Auf Ticketdashboard sieht ein lesender Mitarbeiter nicht den Zeitenbuchen Button
- [x] T79 Auf Ticketdashboard können keine Zeiten mehr gebucht werden wenn Ticket in Abschlussphase ist

**Comment by marlonschlosshauer** [comment]
@sfuerder Ich füge dich hier mal dazu, weil du das gleiche ja auch fürs Card-Design machen musst. Code Teilen wäre hier super 🦅

**Comment by marlonschlosshauer** [comment]
Wäre es realistisch das bis Montag Abend gemerged zu haben?

**Comment by mschwer1** [comment]
Das sollte machbar sein.
