### ISSUE TITLE
IssueDashboard: Untertickets

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#134]
Zeplin Link: [Issue Dashboard](https://zpl.io/bJXOo6J)

- [x] Untertickets anzeigen
- [x] Untertickets einklappbar

da unsere Issues Projektgebunden sind kannst du gerne die "Projekt" Reihe für mehr Platz entfernen.

**Comment by marlonschlosshauer** [comment]
Yoyo, konntest du hiermit schon anfangen? Wie siehst du den Fortschritt hierfür?

**Comment by mschwer1** [comment]
Ich habe schon etwas damit angefangen. Ich gehe davon aus, dass hier die expandTable die beste Option ist, insofern bin ich im Moment noch dabei, die Tickets in die richtige Struktur zu bringen.
