### ISSUE TITLE
IssueSettings: Rest

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#140]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T74 Auf Ticketerstellung und Ticketeinstellung, falls ohne Verhandlung, darf geschätzte Zeit nicht über geschätzer Zeit von Oberticket liegen
- [x] T92 Auf Ticketeinstellungen kann Status "Review" nur ausgewählt werden, wenn alle Untertickets abgeschlossen sind
- [x] T98 Auf Ticketseite bei erstellen von Unterticket benötigt man (fast) selbe Angaben wie Oberticket
- [x] T99 Auf Ticketerstellung bei erstellen von Unterticket können manche Angaben abweichen (siehe Ph.)
- [x] T101 Auf Ticketerstellung kann Unterticket weder in Abschlussphase noch in Review Status hinzugefügt werden
- [x] T102 Auf Ticketerstellung bei erstellen von Unterticktes werden manche Werte vererbt (siehe Ph.)
- [x] T103 Auf Ticketerstellung bei erstellen von Unterticket ist Verhandlung automatisch ausgeschalten
- [x] T108 Auf Ticketeinstellungen werden Vorgänger angezeigt
- [x] T109 Auf Ticketeinstellungen können Vorgänger hinzugefügt/entfernt werden
- [x] T110 Auf Ticketeinstellungen darf einem externen Ticket kein interner internes Ticket als Vorgänger hinzugefügt werden
- [x] T111 Auf Ticketeinstellungen dürfen nur Vorgänger hinzugefügt werde, die nicht in Abschlussphase sind
- [x] T112 Auf Ticketeinstellungen dürfen nur Vorgänger hinzugefügt werde, die weder Ober/Unterticket des Tickets sind

Außerdem: 
- [x] Fortschritt eintragen/bearbeiten

**Comment by marlonschlosshauer** [comment]
@BenjaminKuerten yoyo hab gerade gemerkt das man garnicht den Fortschritt einstellen kann, das bräuchten wir noch 😂

**Comment by BenjaminKuerten** [comment]
Implementiert #196
