### ISSUE TITLE
Bericht-Dashboard: Komponente erstellen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#142]
Zeplin Link: [Berichte Projektfortschritt](https://zpl.io/amGJmNm)
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T49 Auf Ticketdashboard kann Kunde "Zusammenfassung" (Arbeitszeiten) einsehen (Button auf Dashboard wird von Moritz und Sebastian gemacht) 
- [x] T50 Auf Ticketdashboard wird "Zusammenfassung" in Dialog geöffnet (siehe Zeplin)

**Comment by WhiroWhat** [comment]
T49: Also durch ein Button auf dem Ticketdashboard wird ein Dialog geöffnet auf dem man eine Übersicht über den Fortschnitt bzw. die Zeiten bekommt?
Verstehe ich den Inhalt richtig? Wie stellst du dir das genau vor?
Ich finde kein Beispiel zu dem Dialog auf Zeplin kannst du mir das verlinken?

![image](https://user-images.githubusercontent.com/48799541/119654967-4d9cf280-be29-11eb-9b8d-76b228d34069.png)
Das sind die einzigen Sachen zum Ticketdashboard die ich sehe.

**Comment by marlonschlosshauer** [comment]
>  Verstehe ich den Inhalt richtig? Wie stellst du dir das genau vor?

Yes

>  Ich finde kein Beispiel zu dem Dialog auf Zeplin kannst du mir das verlinken?

Der Dialog beinhaltet [dieses Fenster](https://app.zeplin.io/project/5fc7e3d3f6fd070b92854d83/screen/5ffc967b46a8499a28ff0048). Also eigentlich wieder das IssueDashboard (mit winzigen Änderungen). Ist pures busy-work, also auch gerne eigene Ideen einbringen. Für den Dialog würde ich den [ng-zorro Modal](https://ng.ant.design/components/modal/en) nehmen.

**Comment by WhiroWhat** [comment]
Also es ist eine Zusammenfassung für alle Tickets und nicht für ein bestimmtes?

**Comment by marlonschlosshauer** [comment]
Ist ehrlich gesagt in jetzigem Design komplett nutzlos, also falls dir was zum pimpen einfällt, das der Kunde einen guten überblick über Fortschritt und Zeit bekommt, nur zu!

**Comment by WhiroWhat** [comment]
> Ist ehrlich gesagt in jetzigem Design komplett nutzlos, also falls dir was zum pimpen einfällt, das der Kunde einen guten überblick über Fortschritt und Zeit bekommt, nur zu!

ich denke drüber nach
