### ISSUE TITLE
Issue: Rest

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#143]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T21 Nur Mitarbeiter mit Schreibrecht (oder Projektleiter), Kunde als Autor und Firma sehen Bearbeiten Button
- [x] T26 Nur Mitarbeiter und Firma sieht in Ticketansicht den Bereich "Zeiten" 
- [x] T55 Auf Ticketansicht bei "Zusammenfassung" darf Zeitschätzung nicht weniger als Zeitschätzung aller Untertickets sein
- [x] T67 Auf Ticketansicht in "Zusammenfassung" kann Zusammenfassung nur von Projektleiter erstellt werden
- [x] T78 Auf Ticketansicht kann Kunde, Firma und Projektleiter Ticket abbrechen

Warte hier bis #131 fertig ist, das keine Konflikte kommen.

**Comment by Namo2** [comment]
@marlonschlosshauer werde das AP nicht bis mitternacht fertig machen können.
Falls #131 bis morgenfrüh fertig ist, werde ich schauen, dass ich bis Dienstag morgen fertig bin

**Comment by marlonschlosshauer** [comment]
@Namo2 yoyo macht dir keine Sorgen 🐶  Falls du morgen Zeit hast könntest du Sebastian anschreiben und ihn fragen ob er bei etwas Hilfe brauchen könnte.

**Comment by Namo2** [comment]
Für T21 muss der Kunde auch den Bearbeiten Knopf sehen um M24 zu erfüllen (Nur wenn dieser der Autor ist)

**Comment by marlonschlosshauer** [comment]
Yo. Hab T21 geupdated.
