### ISSUE TITLE
Firma kann auf IssueDashboard:Card Zeitstarten, auf Table nicht

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#147]
**Beschreibung des Bugs**
Mein Account (Firma) der weder Projekt noch Ticket zugeteilt ist, kann auf Card die Zeitmessung starten/stoppen, aber auf Table nicht. 

**Reproduktions Schritte**
1. Als "MSchlosshauer" einloggen
2. "Projekt 2" auswählen
3. Falls Table Design: Zeitmessung kann nicht gestartet werden
4. Card Design auswählen
5. Irgendein Ticket Zeitmessung starten
6. Zu Table Design wechseln
7. Zeitmessung kann nicht gestoppt werden

![Screen Shot 2021-06-01 at 11 18 04](https://user-images.githubusercontent.com/24259317/120299888-ba9e0580-c2cb-11eb-9aea-3c1d19b9e3d2.png)
![Screen Shot 2021-06-01 at 11 17 53](https://user-images.githubusercontent.com/24259317/120299896-bc67c900-c2cb-11eb-822a-4e4dc1465c78.png)

**Erwartetes Verhalten**
Was meint ihr, wie soll das verhalten hier aussehen? Ich neige dazu die Firma da einfach machen zu lassen.

**Branches**
- Frontend: feature/IssueDashboardTime
- Backend: master (01.06.2021)

**Comment by sfuerder** [comment]
Sehe gerade, dass Moritz die Funktionalität bezüglich Berechtigung noch hinzugefügt hat. 
Würde sagen, dass diese Funktionalität direkt in den Timer button sollte

**Comment by marlonschlosshauer** [comment]
Hm hm hm. In einer perfekten Welt würde die Komponente dem Button die Logik geben, aber ich sehe das es hier vom Vorteil ist, wenn die Logik nur an einem Platz sich befindet.
Von der Useability würde ich es besser finden wenn auch die Firma überall Zeiterfassungen tätigen könnte. Würdet ihr euch lieber an das Pflichtenheft halten (ich nehme mal an das es so drinsteht wie Moritz das implementiert hat)?

**Comment by sfuerder** [comment]
Ich glaube ich verstehe den ersten Satz nicht so ganz. Wenn die Logik der Button hat ist die Logik doch an nur einem Platz oder? Ansonsten müsste man die selbe Logik auch im Card Design machen.

**Comment by marlonschlosshauer** [comment]
> Ich glaube ich verstehe den ersten Satz nicht so ganz. Wenn die Logik der Button hat ist die Logik doch an nur einem Platz oder? Ansonsten müsste man die selbe Logik auch im Card Design machen.

Wäre das ein riesiges Projekt würde ich es so machen: Dashboard Komponenten übergeben dem Button die Disabled Logik als Funktion, auf welche die beiden Dashboard Komponenten zugriff (über einen Service) haben.
Somit kann der Button für andere Elemente wiederverwendet werden. 
Aber das ist komplett overkill. Das die Logik im Button ist finde ich super.

**Comment by sfuerder** [comment]
Ist das Problem inzwischen behoben? Oder besteht das immer noch?

**Comment by marlonschlosshauer** [comment]
Yep ist fixed 👍 

![Screen Shot 2021-06-15 at 19 30 17](https://user-images.githubusercontent.com/24259317/122097576-1f02ae00-ce10-11eb-9cef-99c1a456672f.png)
