### ISSUE TITLE
Anfragen von Timesheets als Kunde

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-frontend#149]
Im Card Design mache ich eine GET Anfrage an den Issue Endpunkt mit der Option getTimeSheets=true. Sobald ich als Kunde dann das Dashboard aufrufe bekomme ich die Fehlermeldung Forbidde.

Jetzt bin ich mir nicht ganz sicher ob das so richtig ist. Zum Darstellen des Fortschrittsbalken benötige ich die TimeSheets oder? Laut Ph hat kann ein Kunde den Fortschritt einsehen.

Muss ich das anders lösen oder muss da das backen abgeändert werden?

**Comment by marlonschlosshauer** [comment]
Hört sich danach an als müsste das Backend noch erlauben das der Kunde GET auf Timesheets machen kann.

**Comment by pheim1** [comment]
Laut Pflichtenheft darf der Kunde im Prinzip die Timesheets nicht sehen (M6.2)

Zeitgleich darf er es jedoch für den Fortschritt

Ich würde sagen, wir entfernen (M6.2), sodass er es für den Fortschritt abfragen darf. @marlonschlosshauer dürfte so passen oder ?

**Comment by pheim1** [comment]
Alternativ könnte man den Fortschritt aus geschlossen Tickets (untertickets) / gesamt Tickets (untertickets) errechnen.

**Comment by marlonschlosshauer** [comment]
> Alternativ könnte man den Fortschritt aus geschlossen Tickets (untertickets) / gesamt Tickets (untertickets) errechnen.

Der Fortschritt ist auf dem jeweiligen Ticket.

Ich würde sagen entweder streichen wir die Ampel und zeigen nur noch den im Ticket eingetragenen Fortschritt **oder** wir machen einen weiteren Endpunkt bei ``issue/timesheets/consumed`` der dann eben die Verbrauchte Zeit zurückgibt. 
Lehne mich zu letzterem. 

@Madara789 Kennst du dich zufällig mit dem Timesheet Endpunkt aus?

**Comment by Madara789** [comment]
also im IssueDetail gibt es eine Property "TotalWorkedTime" oder so die angibt wie viele stunden auf diesem ticket schon gearbeitet wurden.
Löst das das Problem?

**Comment by marlonschlosshauer** [comment]
Cool das ist genau das was wir brauchen!
