### ISSUE TITLE
Unterticket erstellen Button darf nicht in Review/Abgebrochen/Abgeschlossen angezeigt werden

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#152]
**Beschreibung des Bugs**
"Unterticket erstellen" Button darf nicht in Review/Abgebrochen/Abgeschlossen angezeigt werden

**Branches**
- Frontend: SubTicket
- Backend: master

**Comment by sfuerder** [comment]
Sollte mit dem neuesten commit behoben sein
