### ISSUE TITLE
Fehlermeldung beim Mitarbeiter zuweisen, wenn nichts ausgewählt 

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#161]
**Beschreibung des Bugs**
Beim Klicken auf "Speichern" kommt eine Fehlermeldung. 

**Reproduktions Schritte**
1. Ticket Übersicht
2. Zuweisen
3. Nichts auswählen 
4. Speichern
![Screenshot_7](https://user-images.githubusercontent.com/48795982/120930485-b1f36800-c6ed-11eb-8fc5-5d8eab48debd.png)

**Erwartetes Verhalten**
Kein Error oder Fehlermeldung 
![Screenshot_6](https://user-images.githubusercontent.com/48795982/120930479-ad2eb400-c6ed-11eb-8dae-e430b8b68e50.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by Namo2** [comment]
Kümmere mich dann nächste Woche darum :+1:
