### ISSUE TITLE
Zeitenerfassung starten egal ob Mitarbeiter Zugewiesen ist oder Ticket in Überprüfung

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#163]
**Beschreibung des Bugs**
Ein Mitarbeiter kann immer die Zeit Erfassung starten, auch wenn er nicht zugewiesen ist oder das Ticket noch in der Überprüfung ist.

**Reproduktions Schritte**
1. Einloggen als Mitarbeiter
2. Card Ansicht
3. Play-Button auf nicht zugewiesenem Ticket drücken oder in Überprüfung
4. Zeiterfassung startet

**Erwartetes Verhalten**
Info/Fehlermeldung

**Branches**
- Frontend: main
- Backend: master

**Comment by Namo2** [comment]
Das die Zeiterfassung gestartet werden kann, wenn das Ticket in Überprüfung ist finde ich ansich nicht schlimm.
Immerhin braucht die Überprüfung ja auch Arbeitszeit.

**Comment by marlonschlosshauer** [comment]
Weißt du ob der Fehler nur in "Card" Auftritt?

**Comment by sfuerder** [comment]
Soll ich das aus der Überprüfungsphase auch rausnehmen? Oder wie Claudio meint drin lasse?

**Comment by marlonschlosshauer** [comment]
> Soll ich das aus der Überprüfungsphase auch rausnehmen? Oder wie Claudio meint drin lasse?

Ich würde es drin lassen.
