### ISSUE TITLE
Zeiterfassung wirft Fehler wenn Ticket Abgebrochen ist

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#167]
**Beschreibung des Bugs**
Wenn ein Ticket abgebrochen ist, dann erscheint weiterhin der Play-Button und wirft eine Fehlermeldung beim klicken.

**Reproduktions Schritte**
1. Ticket abbrechen
2. Mitarbeiter klickt auf Play-Button
3. Konsolen-Error
![Screenshot_11](https://user-images.githubusercontent.com/48795982/120931758-5035fc80-c6f3-11eb-99ca-df5e97fd5dc1.png)
![Screenshot_12](https://user-images.githubusercontent.com/48795982/120931761-51672980-c6f3-11eb-96f3-766ce232e0b5.png)

**Erwartetes Verhalten**
Button ist ausgegraut

**Branches**
- Frontend: main
- Backend: master

**Comment by marlonschlosshauer** [comment]
Weißt du ob das in beiden Ansichten der Fall war?

**Comment by sfuerder** [comment]
Mit welchen Zugangsdaten hast du dich eingeloggt und bei welchem Projekt bzw Issue tritt das auf?
