### ISSUE TITLE
Zusammenfassung annehmen wirft Error, wenn Ticket noch in Überprüfen ist

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#168]
**Beschreibung des Bugs**
Wenn ein Ticket in Überprüfen ist und versucht wird die Zusammenfassung zu anzunehmen wird ein Fehler geworfen, dies ist auch korrekt, da das Ticket erst in Verhandlung gesetzt werden muss. Dies sollte aber dem User über eine Fehlermeldung mitgeteilt werden. 

Meine Idee:
Eine andere Lösung wäre es, dass das Ticket ab der ersten Nachricht in Verhandlung gesetzt wird oder spätestens beim Abschicken der Zusammenfassung.

**Reproduktions Schritte**
1. Ticket erstellen 
2. Zusammenfassung erstellen 
3. Versuchen diese anzunehmen
3. Fehler in Konsole
![Screenshot_13](https://user-images.githubusercontent.com/48795982/120932070-9b9cda80-c6f4-11eb-84c9-b68970c0d013.png)

**Erwartetes Verhalten**
Entweder mein Vorschlag oder Fehlermeldung

**Branches**
- Frontend: main
- Backend: master

**Comment by Namo2** [comment]
> Eine andere Lösung wäre es, dass das Ticket ab der ersten Nachricht in Verhandlung gesetzt wird oder spätestens beim Abschicken der Zusammenfassung.

Ich finde die Idee gut, dass der Status spätestens beim Abschicken einer Zusammenfassung automatisch gesetzt wird.
Falls wir der Idee nachgehen würde ich sagen, dass die Implementierung am besten im @gedankenessen/backend vorgenommen wird.

**Comment by Yochyo** [comment]
> Falls wir der Idee nachgehen würde ich sagen, dass die Implementierung am besten im @gedankenessen/backend vorgenommen wird.
An sich spricht nichts dagegen.

**Comment by Yochyo** [comment]
Falls niemand eine bessere Idee hat würde ich das dem nächsten Release beifügen.

**Comment by marlonschlosshauer** [comment]
Finde die Idee sehr gut. Von einem UI Standpunkt wäre es vielleicht besser wenn wir einfach den Button zum senden der Zusammenfassung disablen und eine Warnung anzeigen, aber ich hätte dem hier auch nichts entgegen zu setzen 👍 

@Yochyo Falls du Zeit dafür in den nächsten Tagen findest kannst es gerne implementieren.
