### ISSUE TITLE
"Neues Projekt" Button fehlt manchmal

### ISSUE THREAD

**Issue by Luk-T** [gedankenessen/goose-frontend#172]
**Beschreibung des Bugs**
Der Button "Neues Projekt" auf dem Dashboard, Tab Projekte, wird nicht immer angezeigt.

**Reproduktions Schritte**
Es wurde bisher noch kein Projekt angelegt, die Liste ist komplett leer.
Nachdem man einmal im Kunden Tab war, wird der Button nie mehr angezeigt. Bin mir aber nicht 100%-ig sicher, dass dies wirklich die ganze Bedingung ist.

**Erwartetes Verhalten**
Der Button soll immer da sein

**Branches**
- Live

**Comment by Namo2** [comment]
Der Bug ist leider schon bekannt.
Ich selbst weiß leider nicht wie ich diesen Fixen kann.

@marlonschlosshauer @BenjaminKuerten wollt ihr mit mir vllt die Tage nochmal draufschauen?

**Comment by BenjaminKuerten** [comment]
Klar, können wir morgen nach unserer Mathe-Lerngruppe machen. @marlonschlosshauer passt dir 19:30 Uhr oder 20:00 Uhr?

**Comment by Namo2** [comment]
Perfekt

**Comment by marlonschlosshauer** [comment]
Passt 😎👍
