### ISSUE TITLE
Authorisierung kommt nicht mit verschiedenen Anmeldungen in verschiedenen Tabs klar.

### ISSUE THREAD

**Issue by Luk-T** [gedankenessen/goose-frontend#173]
**Beschreibung des Bugs**
Mehrere verschiedene Logins in verschiedenen Tabs sorgen für Probleme, und erlauben es beim Erstellen von Tickets das Rechtesystem zu umgehen.

**Reproduktions Schritte**
Anmelden mit Nutzer 1 in einem Tab 1
Anmelden mit Nutzer 2 in einem Tab 2
Erstellt man in Tab 1 jetzt Tickets, wird Nutzer 2 als Autor eingetragen, obwohl er auf das Projekt von Nutzer 1 gar kein Zugriff haben dürfte

**Erwartetes Verhalten**
Entweder Nutzer 1 wird automatisch ausgeloggt, oder Nutzer 1 wird als Autor des Tickets eingetragen

**Branches**
- Live

**Comment by Luk-T** [comment]
@marlonschlosshauer
Ich konnte leider nicht herausfinden, wer sich um die Autorisierung im Frontend gekümmert hat. Hab kein Arbeitspaket gefunden. Weißt du noch, wer das gemacht hat, und assignest ihn bitte?

**Comment by marlonschlosshauer** [comment]
> Ich konnte leider nicht herausfinden, wer sich um die Autorisierung im Frontend gekümmert hat.

Danke fürs nachschauen, da haben aber in der Tat mehrere ihre Finger im Spiel gehabt (@BenjaminKuerten @marlonschlosshauer @Namo2).

> Mehrere verschiedene Logins in verschiedenen Tabs

Ich weiß nicht ob wir uns auf dieses Feature noch Fokussieren können. Ich verstehe das es für das Testen sehr hilfreich wäre, aber wir müssten das Anmelden stark überarbeiten. 

Das wir mehrere Tabs verwenden können (mit dem gleichen Nutzer), hat Benny extra das so eingefügt.  Momentan Speichern wir die Daten im lokalen Speicher. Deswegen wird hier der erste Login, nach dem zweiten, "überschrieben".
