### ISSUE TITLE
IssueVisibility wird bei PUT immer auf "false" gesetzt

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#176]
**Beschreibung des Bugs**
Verhalten beim setzen von ``Visibility`` ist etwas komisch.  Ich denke true = extern (?)
 ``visibility`` ist nur bei einem POST mit "extern" auf ``true``. Wenn ich einen PUT mit "extern" mache wird``false`` gesendet.

Korrektes Verhalten:

**POST Intern = false**
![POST intern = false](https://user-images.githubusercontent.com/24259317/121177686-fef64c00-c85d-11eb-8bd8-0f13d321b037.png)

**POST Extern = true**
![POST extern = true](https://user-images.githubusercontent.com/24259317/121177755-146b7600-c85e-11eb-8a7b-8a9536c48ab4.png)

Falsches Verhalten:

**PUT Extern = false** 
![PUT extern = false](https://user-images.githubusercontent.com/24259317/121177601-e38b4100-c85d-11eb-851b-5088cb434a20.png)

**PUT Intern = false** 
![PUT intern = false](https://user-images.githubusercontent.com/24259317/121177489-bc347400-c85d-11eb-9756-9d1939b18564.png)

**Reproduktions Schritte**
1. Ticket erstellen, mit Visibility "intern"
2. Ändere Ticket, mit Visibility auf "extern"
3. IssueVisiblity hat sich nicht geändert

@BenjaminKuerten @Namo2 Wisst ihr ob wir überhaupt im Pflichtenheft haben das man die ändern kann?

**Branches**
- Frontend: main
- Backend: master

**Comment by marlonschlosshauer** [comment]
(btw hab das gepostet weil ich schon die screenshots und den text hatte und mir dann eingefallen ist das wir wahrscheinlich einfach keine PUT auf visibility zulassen :( sadge)

**Comment by BenjaminKuerten** [comment]
Fix #196
