### ISSUE TITLE
Typ eines Tickets sollte nicht änderbar sein

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#177]
**Beschreibung des Bugs**
Typ kann geändert werden, wenn das Ticket bearbeitet wird. Ich glaube es wäre besser für das Backend wenn wir das nicht zulassen. 

**Erwartetes Verhalten**
Wenn festgestellt wird das das Ticket bearbeitet wird könnten wir das Typ Feld auf ``[disabled]`` machen

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
#196
