### ISSUE TITLE
Status "Abgeschlossen" gibt es nicht wenn in Status "Review"

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#179]
http://localhost:4200/609421f4d837b069802b738e/projects/60bf4e864f524d084725b185/issues/60bf5e8bd76b6d225409a637/edit

![kein  abgeschlossen](https://user-images.githubusercontent.com/24259317/121182864-c8bbcb00-c863-11eb-84ab-08bc534b481f.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
Fix #196
