### ISSUE TITLE
Geschätzte Zeit anzeigen bevor Zusammenfassung angenommen

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-frontend#182]
Hey,
soll auf dem Ticketdashboard die geschätzte Zeit schon eingetragen sein, bevor man die Zusammenfassung annimmt?

Als Beispiel:
![grafik](https://user-images.githubusercontent.com/48796374/121278442-dfe5d180-c8d2-11eb-8682-b4de6a762130.png)
Bei Oberticket #1 kann man sehen, dass wir eine geschätzte Zeit von 6 Stunden haben.
Die Zeit kommt von der letzten geschickten Zusammenfassung. 
Allerdings wurde diese noch nicht angenommen.

**Comment by marlonschlosshauer** [comment]
Ist OK 😎 👍
