### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#185]
Wir brauchen noch alle Fehlermeldungen für das [Pflichtenheft](https://docs.google.com/document/d/1sEfx8s7TNK57mixii6nnmde-BA_Cg0rQ6gjhfIwLcpw/edit#). 
Welche haben wir überhaupt im Frontend? Registrierung, Login und Ticketbearbeiten fällt mir ein. 
Wäre super wenn jeder die Sammeln könnte (oder ich die von euch finden kann).

**Comment by WhiroWhat** [comment]
Diese fallen mir ein:
1. Falsche Logindaten
2. Nicht alle Felder ausgefüllt bei Registrierung
3. Firmenname nicht verfügbar bei Registrierung
4. Versuch leeres Requirement hinzufügen 
(Errormeldung dafür könnte noch angepasst werden)
Momentane Meldung zu 4:
![image](https://user-images.githubusercontent.com/48799541/121791499-9eaf3380-cbea-11eb-99e4-396ac569f3f4.png)

**Comment by Namo2** [comment]
Issue Assigned:
-       Title: 'Error beim Hinzufügen eines Benutzers',
        Fehler: 'Bitte wählen Sie einen Benutzer aus der Liste aus, welcher hinzugefügt werden soll',
        
Projekt Settings:
-       Title: 'Error beim hinzufügen eines Mitarbeiters',
        Fehler: 'Bitte füllen Sie alle Felder aus (Mitarbeiter + Rechte)',
   
-       Title: 'Error beim hinzufügen eines Mitarbeiters',
        Fehler: 'Es gibt bereits einen Projektleiter',
        
-       Title: 'Error beim entfernen eines Status',
        Fehler: 'Der Status wird im Moment noch von einem Ticket verwendet',
        
-       Title: 'Error beim hinzufügen eines Status',
        Fehler: 'Bitte füllen Sie alle Felder aus (Statusname + Phase)',
        
-       Title: 'Error beim Erstellen/Updaten eines Projektes',
        Fehler: 'Bitte füllen Sie alle Felder aus (Projektname + Kunde)',

TimeSheets:
-       Title: 'Error beim ändern der gebuchten Zeit',
        Fehler: 'Das Startdatum darf nicht hinter dem Enddatum liegen',

-       Title: 'Unauthorized',
        Fehler: 'Sie sind nicht berechtigt die gebuchte Zeit zu ändern oder die Abschlussphase wurde erreicht',

**Comment by sfuerder** [comment]
Card Design:
```
Title: 'Error beim laden der Tickets.'
Fehler: ''
```
```
Title: 'Error beim Speichern des TODOs.'
Fehler: ''
```

Issue Component:
```
Title: 'Error beim laden des Tickets.'
Fehler: ''
```
```
Title: 'Das Requirement konnte nicht gespeichert werden.'
Fehler: ''
```
```
Title: 'Das Requirement konnte nicht entfernt werden.'
Fehler: ''
```

**Comment by BenjaminKuerten** [comment]
`Title: 'Fehler beim ändern des Tickets',
 Fehler: 'Statusänderung nicht möglich`

`Title: 'Fehler beim ändern des Tickets',
 Fehler: 'Mindestens ein Unterticket ist noch nicht abgeschlossen`

`Title: 'Fehler beim speichern des Tickets',
 Fehler: 'Bitte füllen Sie alle Pflichtfelder aus`

`Title: 'Fehler',
 Fehler: 'Die Deadline darf nicht vor dem Start-Datum sein`

`Title: 'Vorgänger',
 Fehler: 'NAME ist nicht als Vörgänger möglich`

`Title: 'Vorgänger',
 Fehler: 'Löschen von NAME ist nicht möglich`

**Comment by marlonschlosshauer** [comment]
@mschwer1 @WhiroWhat Ich bräuchte noch von euch beiden die Fehlermeldungen (falls eure Komponenten welche haben). Falls ihr keine habt könnt ihr euch un-assignen.

**Comment by WhiroWhat** [comment]
> @mschwer1 @WhiroWhat Ich bräuchte noch von euch beiden die Fehlermeldungen (falls eure Komponenten welche haben). Falls ihr keine habt könnt ihr euch un-assignen.

Hab meine Ursprüngliche Nachricht editiert. Passt das so?
