### ISSUE TITLE
Jedem Nutzer wird gleiche aktive Zeiterfassung (zu Ticket) angezeigt

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#194]
**Beschreibung des Bugs**
Habe mit CWetzel eine Zeiterfassung auf Ticket "Oberticket \#\2" in "DHL Postfach" gemacht. WMendat und MSchlosshauer sehen nun kein ▶️ bei dem Ticket, sondern auch ein ⏹ (obwohl weder noch eine Zeiterfassung gestartet hat). 

Wenn ich die Erfassung stoppe und mit WMendat starte, sieht auch CWetzel diese. CWetzel ist Projektleider in dem Projekt, kann deswegen die Zeiterfassung von WMendat stoppen. 

@sfuerder @mschwer1  Meinst ihr hier wurde der Endpunkt falsch angefragt oder ist das ein Fehler im Backend sein?
@mschwer1 @sfuerder bitte schaut ob es ein Fehler im Frontend ist, falls nicht meldet euch bitte demnächst bei @Madara789 

**Daten**
URL: http://51.254.157.180:5000/api/issues/60bf666ad76b6d225409a647/timeSheets/60c8e6a53f7bf23add138d16
Request: http://51.254.157.180:5000/api/issues/60bf666ad76b6d225409a647/timeSheets/60c8e6a53f7bf23add138d16

**Fehlermeldung**
Wenn ich mit WMendat versuche die Zeiterfassung von CWetzel zu stoppen kriege ich (korrekterweise) folgende Meldung:
```js
{"message":"Your are not allowed to update a timesheet.","status":403,"type":"HttpStatusException","stackTrace":""}
```

CWetzel:
![image](https://user-images.githubusercontent.com/24259317/122100115-1a8bc480-ce13-11eb-8c7a-70d40d31ff51.png)

WMendat:
![image](https://user-images.githubusercontent.com/24259317/122100084-1069c600-ce13-11eb-85c4-dcce23a4fb3b.png)

Wenn ich als WMendat auf Stop drücke steht in dem Request auch "Claudio" drin:
![image](https://user-images.githubusercontent.com/24259317/122100386-69395e80-ce13-11eb-95ae-85552b30180f.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by mschwer1** [comment]
Ich habe im TimerService nachgeschaut und ich denke, dass Problem war, dass in der isTimerRunningTimesheets-Methode nicht nach User überprüf wurde, also wurde einfach das erste TimeSheet verwendet, das noch nicht beendet wurde. Sollte also mit den Frontend-Änderungen behoben sein.
