### ISSUE TITLE
IssueComponent

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#2]
- [x] Titel, Beschreibung und Informationen (Status, Autor, Typ) anzeigen
- [x] Bearbeiten Button
- [x] Navigation links
- [x] Dynamisches Laden der aktuell aktiven Komponente
- [x] Neuer IssueService integrieren

**Comment by marlonschlosshauer** [comment]
@sfuerder wie weit bist du ungefähr mit den neuen Services ? Die neue API ist [online](http://51.254.157.180:5000/swagger/index.html).

**Comment by sfuerder** [comment]
Ich würde morgen evtl spätestens am Montag morgen die Services überprüfen.

**Comment by marlonschlosshauer** [comment]
Yoyo @sfuerder hättest du hier noch was zu tun ?

**Comment by sfuerder** [comment]
Mir fällt nichts ein was noch fehlt, außer die anderen Komponenten zu integrieren, sobald diese erstellt wurden

**Comment by marlonschlosshauer** [comment]
Gut dann würde ich dieses AP als abgeschlossen ansehen 👍
