### ISSUE TITLE
Ticket Einstellungen: Mehrere Vorgänger aufeinmal hinzufügen

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-frontend#200]
**Beschreibung des Bugs**
Wenn man in einem Ticket mehrere Vorgänger aufeinmal hinzufügen möchte, dann wird nur eins davon gespeichert.

**Reproduktions Schritte**
1. Mehrere Tickets erstellen.
2. In einem der Tickets alle anderen als Vorgänger hinzufügen
3. Speichern

**Erwartetes Verhalten**
Alle Tickets werden als Vorgänger hinzugefügt.

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
Fix #103
