### ISSUE TITLE
Max. länge bei allen Input feldern

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#201]

**Comment by BenjaminKuerten** [comment]
👍

**Comment by Namo2** [comment]
Habs für die ProjektSettings implementiert +1

**Comment by marlonschlosshauer** [comment]
@sfuerder @mschwer1 @WhiroWhat Hattet ihr schon einen Moment um bei euch max-lenght bei den Inputs hinzuzufügen?

**Comment by WhiroWhat** [comment]
jo ist implementiert.  :+1:
