### ISSUE TITLE
Ticket im Reviewstatus hat verschobene Buttons

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-frontend#202]
**Beschreibung des Bugs**
Wenn man bei einem Ticket in den Review-Status geht sind die Buttons komisch angeordnet. 
("Unterticket erstellen"-Button wird ausgebendet)

**Reproduktions Schritte**
1. Ticket erstellen
2. Zusammenfassung erstellen und abschicken
3. In Reviewstatus gehen
![image](https://user-images.githubusercontent.com/48799541/122689888-3d104a00-d226-11eb-9aed-8d447fe5b887.png)

**Erwartetes Verhalten**
Buttons sollten direkt nebeneinander angeordnet sein.

**Branches**
- Frontend: main
- Backend: master

**Comment by Namo2** [comment]
@sfuerder hast du eine Idee woran das liegen könnte. Für mich sah der Code eigentlich richtig aus.
Falls du keine Zeit haben solltest kann ich mich auch nochmal dran setzen. Würde das ganze dann aber zu einer Flexbox umschreiben
