### ISSUE TITLE
Kunde kann kein Ticket mit Vorgängern erstellen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#212]
**Erstellen**

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/24259317/123516697-bcc26c80-d69d-11eb-8553-214784bffd36.png">

**Bearbeiten**
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/24259317/123516722-d5328700-d69d-11eb-9c64-dc765febae22.png">

**Comment by marlonschlosshauer** [comment]
Mitarbeiter kann hingegen:
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/24259317/123516743-eaa7b100-d69d-11eb-9b6a-3acfa4370530.png">

**Comment by BenjaminKuerten** [comment]
Habe ich absichtlich deaktiviert. Die Vorgänger werden doch nicht vom Kunden gesetzt, sondern vom Team
