### ISSUE TITLE
Vorgänger können beim erstellen von Issue nicht hinzugefügt werden

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#215]
Id des Tickets gibt es noch nicht, wird für Predecessor Endpunkt verwendet um zu setzen. @Yochyo kann man beim erstellen von einem Ticket die Vorgänger mit geben?
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/24259317/123517433-2d1ebd00-d6a1-11eb-80b4-6e2b2f8e7f6f.png">

**Comment by BenjaminKuerten** [comment]
Das sollte am backend liegen, da das Ticket noch nicht erstellt ist. Meine Lösung (schnell und einfach) wäre, dass das Feld beim erstellen ausgegraut ist

**Comment by BenjaminKuerten** [comment]
Bzw da ich die Ticket ID vor dem erstellen noch nicht habe

**Comment by Yochyo** [comment]
Im Backend ist es so vorgesehen, dass ein Issue erst erstellt wird und danach die Vorgänger gesetzt werden.

**Comment by marlonschlosshauer** [comment]
yoyo @BenjaminKuerten hau mal auf disabled in create bitte danke

**Comment by BenjaminKuerten** [comment]
Gut, wird gemacht

**Comment by BenjaminKuerten** [comment]
fixed
