### ISSUE TITLE
Keine Fehlermeldung, wenn ein Mitarbeiter den Status eines Issues ändern möchte

### ISSUE THREAD

**Issue by pheim1** [gedankenessen/goose-frontend#218]
**Beschreibung des Bugs**
Versucht ein Mitarbeiter den Status eines Issues von z.B. Wartend -> Bearbeitung zu ändern, bekommt das Frontend vom Backend ein 403, aber das Frontend zeigt keine Meldung/Fehler an.

**Reproduktions Schritte**
1. Issue bearbeiten
2. Networktab öffnen
3. Status als Mitarbeiter wechseln

**Erwartetes Verhalten**
Es erscheint eine Fehlermeldung, dass man nicht über die erforderlichen Rechte verfügt.

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
Bau ich heute Abend noch ein, muss dann noch ins Pflichtenheft

**Comment by BenjaminKuerten** [comment]
fixed
