### ISSUE TITLE
Zeitschätzung setzt sich zu "1" zurück

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#219]
**Beschreibung des Bugs**
Eingabe setzt sich bei focus out auf "1" zurück. 

https://user-images.githubusercontent.com/24259317/123551170-f1ebbf00-d770-11eb-8ec6-70214be101d1.mov

**Reproduktions Schritte**
1. Erstelle Ticket als Typ Fehler
2. Bearbeite Ticket
3. Gebe bei Zeitschätzung Zahl ein

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
Hat das Oberticket eine größere Zeitschätzung?

**Comment by marlonschlosshauer** [comment]
> Hat das Oberticket eine größere Zeitschätzung?

Anscheinend hatte ich mich beim ersten eintippen verdrückt und bei weiteren Änderungen kann man es nicht mehr ändern.
Ich weiß gerade nicht ob man die Zeitschätzung später noch ändern sollte, aber so scheint mir der Bug kein Problem zu sein. Was meinst du?

**Comment by marlonschlosshauer** [comment]
Nevermind es macht es manchmal 🙃 Ich versuche den Bug nochmal zu provozieren.
