### ISSUE TITLE
Status lässt sich nicht ändern

### ISSUE THREAD

**Issue by pheim1** [gedankenessen/goose-frontend#220]
**Beschreibung des Bugs**
![state](https://user-images.githubusercontent.com/58334704/123551256-47c06700-d771-11eb-8dbd-40bef156b9cd.gif)

Konnte nicht ausschließen, ob es evtl. am Backend liegt.

**Reproduktions Schritte**
1. Status ändern in Bearbeitung
2. Status Überprüfen

**Erwartetes Verhalten**
Status wird verändert oder falls dies nicht möglich ist (Pflichtenheft) sollte es vom FE nicht möglich sein.

**Branches**
- Frontend: main
- Backend: master

**Comment by marlonschlosshauer** [comment]
Von Wartend kann man nicht weg, außer man ändert das Startdatum. Trotzdem sehe ich als Bug das es den Status nicht anzeigt. 
Das es immer alle Statuse anzeigt ist halt wirklich dumm 🤔

**Comment by pheim1** [comment]
> Von Wartend kann man nicht weg, außer man ändert das Startdatum.

Ok, das hatte ich nicht auf dem Schirm. Werde aber mal die Prio reduzieren.

**Comment by BenjaminKuerten** [comment]
Die Liste der verfügbaren Statuse kann ich aber im Frontend nicht entscheiden, da es ja auch individuelle gibt. Müsste dann direkt vom Endpunkt kommen, sollte ja quasi auch schon eingebaut sein über den „ist möglich Check“

**Comment by pheim1** [comment]
Welche Phase ein Status hat, siehst du im Issue-DTO, somit kann man ja die ungeeigneten rausfiltern.

**Comment by marlonschlosshauer** [comment]
Zusätzlich zu dem: Wartend und Blockiert kann man nie auswählen (oder davon ändern).

**Comment by marlonschlosshauer** [comment]
Um die Logik zu vervollständigen:

Der Status Review (Bearbeitungsphase) kann hingegen aber zur Abschlussphase. 
Bei jedem Status können Projektleiter, Autor oder Firma das Ticket auch in den Abbrechen Status bringen.

**Comment by marlonschlosshauer** [comment]
Da könnte mit dem anderen zu viel werden. Falls Zeit knapp wird könnten wir es aber auch an jemanden anderen weitergeben.

**Comment by BenjaminKuerten** [comment]
"fixed"
