### ISSUE TITLE
Zeitschätzung wird manchmal nicht angezeigt

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#221]
![image](https://user-images.githubusercontent.com/24259317/123551675-1d6fa900-d773-11eb-950c-663d17311ace.png)

![image](https://user-images.githubusercontent.com/24259317/123551687-22345d00-d773-11eb-8aba-42745f07acfb.png)

**Comment by BenjaminKuerten** [comment]
![image](https://user-images.githubusercontent.com/48795982/123551832-b999b000-d773-11eb-828c-77ac8278a73b.jpg)
Schau ich mir später mach genauer an

**Comment by marlonschlosshauer** [comment]
yoyo, bei dem kein stress, hab es auf medium gemacht weil es doch wichtig ist aber ich weiß zu wenig darüber um es zu erklären. ist erstmal hier das es nicht untergeht 👍

**Comment by BenjaminKuerten** [comment]
fixed
