### ISSUE TITLE
Keine Fehlermeldung bei überschätzen von Zeit

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#222]
**Beschreibung des Bugs**
Wenn die gesamt geschätzte Zeit der Untertickets die von dem Oberticket übersteigt, wirft das Backend einen Fehler. Der wird im Frontend nicht angezeigt.

![image](https://user-images.githubusercontent.com/24259317/123551793-848d5d80-d773-11eb-8367-b2fb3f0d68df.png)

![image](https://user-images.githubusercontent.com/24259317/123551802-8e16c580-d773-11eb-9b2e-7615995a5574.png)

![image](https://user-images.githubusercontent.com/24259317/123551842-cae2bc80-d773-11eb-9321-8e9aec84e564.png)

**Reproduktions Schritte**
1. Erstelle Oberticket,
2. Schätze Zeit z.B. 10 Stunden
3. Erstelle Unterticket
4. Schätze 11 Stunden in Unterticket

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
fixed
