### ISSUE TITLE
Zeiterfassungen sind nicht als Mitarbeiter mit Schreibrecht möglich

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#223]
Mitarbeiter (Schreibreicht):
![image](https://user-images.githubusercontent.com/24259317/123552371-1bf3b000-d776-11eb-9c56-3cfe152a8a4d.png)
![image](https://user-images.githubusercontent.com/24259317/123552512-bd7b0180-d776-11eb-82fe-7fd6f0665104.png)

Mitarbeiter (Projektleiter) **ist korrekt**:
![image](https://user-images.githubusercontent.com/24259317/123552388-39287e80-d776-11eb-8a97-62e8e3f17f28.png)

Ich weiß nicht mehr wie wir uns bei der Firma entschieden haben, aber die kann auch keine Zeit erfassen, ist für mich aber kein Beinbruch:
Firma:
![image](https://user-images.githubusercontent.com/24259317/123552375-28780880-d776-11eb-9ce0-5ed035aa42e7.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by pheim1** [comment]
> Ich weiß nicht mehr wie wir uns bei der Firma entschieden haben, aber die kann auch keine Zeit erfassen, ist für mich aber kein Beinbruch:

Backendseitig dürfte die Firma das.

**Comment by marlonschlosshauer** [comment]
> Backendseitig dürfte die Firma das.

Dann wäre es super wenn die das auch im Frontend könnte 🥼

**Comment by sfuerder** [comment]
Muss der Mitarbeiter dem Ticket nicht zugewiesen sein, um eine Zeiterfassung zu starten?

**Comment by marlonschlosshauer** [comment]
Hm, das hört sich richtig an 🤔 Dann Probiere ich es nochmal nachdem ich zugewiesen habe. Sorry, hatte das nicht auf dem Schirm.
