### ISSUE TITLE
Default Auswahl von Typ in Tickets

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#224]
```
F46: Verhandlung ist automatisch in Untertickets ausgeschalten
M46.0:
Bei dem Erstellen des Untertickets kann ausgewählt werden ob in der Verhandlungsphase oder in der Bearbeitungsphase gestartet werden sollte 
```

Wie viel Arbeit wäre es den Typ "Feature" automatisch beim erstellen von Ticket auszuwählen und Typ "Fehler" bei einem Unterticket?

**Comment by BenjaminKuerten** [comment]
Ich würde Untertickets einfach immer in "bearbeiten" starten (egal ob Fehler oder Feature)

**Comment by marlonschlosshauer** [comment]
Useability kompletter murx aber ich muss sagen, ich respektiere die minimierung der arbeit 👍 
Können wir so machen.

**Comment by BenjaminKuerten** [comment]
fixed
