### ISSUE TITLE
Die Visibility der Tickets wird in den Issue-Settings nicht richtig angezeigt.

### ISSUE THREAD

**Issue by WhiroWhat** [gedankenessen/goose-frontend#227]
**Beschreibung des Bugs**
Bei jedem Ticket egal ob "Intern" oder "Extern" wird immer "Extern" in den Issue-Settings angezeigt. 

**Reproduktions Schritte**
1. Issue mit Visibility "Intern" erstellen.
2. Auf Einstellungsbutton klicken.
3. Visibility ist "Extern"

![image](https://user-images.githubusercontent.com/48799541/123560992-1ada7700-d7a6-11eb-8419-c8e6d74ae395.png)

![image](https://user-images.githubusercontent.com/48799541/123561003-25950c00-d7a6-11eb-9436-e1df0c47a9cd.png)

**Branches**
- Frontend: main
- Backend: master

**Comment by BenjaminKuerten** [comment]
fixed
