### ISSUE TITLE
Startdatum soll nur in Verhandlungsphase änderbar sein

### ISSUE THREAD

**Issue by Yochyo** [gedankenessen/goose-frontend#228]
Wenn das Startdatum eines Issues in der Bearbeitungsphase geändert wurde (und das Startdatum in der Zukunft war) wird der Status nicht auf Wartend gesetzt. Wir haben uns in https://github.com/gedankenessen/goose-backend/issues/147 dazu entschieden, dass das Startdatum nur in der Verhandlungsphase änderbar ist. Könntest du das im Frontend anpassen? @BenjaminKuerten

**Comment by BenjaminKuerten** [comment]
Ja

**Comment by BenjaminKuerten** [comment]
fixed
