### ISSUE TITLE
IssueSummary

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#27]
Aufgaben: 
- [x] T66 Auf Ticketansicht in "Zusammenfassung" kann Zusammenfassung erstellt werden
- [x] T31 Auf Zusammenfassungs Seite (Requirements) kann Projektleiter Zusammenfassung abschicken 

Links: [Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804), [Zeplin](https://zpl.io/a8Xd3PQ)

**Comment by marlonschlosshauer** [comment]
Hey hey Willy hat mir gesagt das er dir die neue API geschildert hat. Hast du eine Abschätzung wann ein für das Issue PR bereit wäre ?

**Comment by mschwer1** [comment]
Zum Schildern sind wir noch nicht gekommen, aber ich hoffe mal, dass ich den Großteil dieses Wochenende hinbekommen werde.

**Comment by marlonschlosshauer** [comment]
Hey Hey konntest du schon weiteren Fortschritt machen ?

**Comment by marlonschlosshauer** [comment]
"- T79 Auf Ticketdashboard können keine Zeiten mehr gebucht werden wenn Ticket in Abschlussphase ist" passt da überhaupt nicht rein, sorry das war ein Fehler. Hab das entfernt und mit einer anderen Aufgabe ausgetauscht. Der Check für Projektleiter ist erstmal nicht nötig. Meinst du das kriegst du noch rein bis morgen ?
Sorry für die Änderung so kurz vor der Deadline.
