### ISSUE TITLE
IssueAssigned

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#29]
- [x] Layout
- [x] Mitarbeiter hinzufügen
- [x] Mitarbeiter entfernen
- [x] Mitarbeiter von DB laden

[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T57 Auf Ticketansicht unter "Zugewiesen" werden alle zugewiesenen Mitarbeiter angezeigt werden
- [x] T58 Auf Ticketansicht unter "Zugewiesen" können Mitarbeiter hinzugefügt/entfernt werden

**Comment by Namo2** [comment]
Moin Loide,

bin gerade am bearbeiten der zugewiesenen Mitarbeiter.
Laut Pflichtenheft M22 soll es möglich sein bei dieser Ansicht Mitarbeiter hinzuzufügen oder zu entfernen.
Haben allerdings diese Funktionen nicht auf dem Mock-Up drauf.
Persönlich hätte ich das ganze wieder mit einem Tollen X Knopf (in der jeweiligen Card) zum entfernen umgesetzt aber ich hab in Erinnerung, dass wir darüber mal länger diskutiert haben.
Weiß noch jemand was wir damals genau besprochen haben @gedankenessen/frontend @Luk-T ?

**Comment by marlonschlosshauer** [comment]
Ist mir auch beim erstellen von der Tracebility aufgefallen. 
Die Idee mit dem X gefällt mir. Vielleicht oben noch ein eine Input Leiste, in der man den Namen eingeben und über einen klick hinzufügen kann.

**Comment by Namo2** [comment]
@marlonschlosshauer 
Können im Input Feld nur User ausgewählt werden welche auch ProjectUser sind?

**Comment by marlonschlosshauer** [comment]
> @marlonschlosshauer
> Können im Input Feld nur User ausgewählt werden welche auch ProjectUser sind?

Yo nur ProjectUser
