### ISSUE TITLE
Issue Services

### ISSUE THREAD

**Issue by sfuerder** [gedankenessen/goose-frontend#30]
Ich habe jetzt die Services entsprechend angepasst. Jedoch sind noch ein paar dinge aufgekommen bei denen ich mir nicht so ganz sicher bin.

- @Yochyo Zurzeit gibt es nur den Endpunkt IssuePredecessor fehlt da nicht noch IssueSuccessor? Und außerdem gibt es dort nur die Möglichkeit für ein PUT und DELETE. Da bräuchten wir noch ein GET oder?
- Beim Parent Endpunkt ist mir nicht ganz klar für was dort der firstname und Lastname stehen soll. Ist dieser Endpunkt vom Prinzip her nicht genauso aufgebaut wie die Endpunkte Predecessor und Successor?
- @marlonschlosshauer Wie gehe ich in Angular mit Parametern hinter dem ? in einer URL am besten um. Wie baue ich das in die Services mit ein?

**Comment by marlonschlosshauer** [comment]
>     * Wie gehe ich in Angular mit Parametern hinter dem ? in einer URL am besten um.

Einzelne Funktionen wären zu viele Optionen. Alle Endpunkt Parameter optional als Parameter der Funktion zu geben wäre, finde ich, nervig wenn man z.B. ``all`` haben möchte. 
Was haltest du davon ein JSON mit den flags zu übergeben ? 

Sowas wie das:
``` ts
getIssue(projectId: string, issueId: string, parameters?: {}): Observable<Issue> {
    return this.httpClient
      .get<Issue>(`${this.getURL(projectId)}/${issueId}`, { ...this.httpOptions, params: parameters })
      .pipe(catchError(this.base.errorHandle));
  }
```
