### ISSUE TITLE
Firefox wirft CORS Fehler ohne registrierte Domain

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#46]
Teste Vertical Slice und kann kein Projekt erstellen weil der ProjectService noch kein Authorized Header sendet. 

Habe in ``hotfix/auth-header-in-services`` einen kleinen Fix erstellt. Einen dritten Service der die Request Funktionen abstrahiert und den Header hinzufügt, wenn der von AuthService gegeben ist. 

@sfuerder @BenjaminKuerten @pheim1 Fällt euch da eine Langzeit Lösung ein ? Ich schon ein paar mal zu dem Thema "Interceptor" gehört, selber hab ich das aber noch nie gemacht.

**Comment by pheim1** [comment]
https://github.com/gedankenessen/blob-frontend/blob/master/Blob/src/app/auth/auth-http.interceptor.ts

**Comment by marlonschlosshauer** [comment]
Hab den Interceptor in ``hotfix/interceptor`` kopiert. Kriege jetzt aber CORS Fehler wenn ich auf Issues & Users zugreife (Project scheint zu funktionieren). 

Ist der Endpunkt noch nicht bereit dafür ?
<img width="1279" alt="Screen Shot 2021-04-09 at 12 04 03" src="https://user-images.githubusercontent.com/24259317/114164720-e9cb7280-992b-11eb-9d2e-3a10bf2035a8.png">
<img width="1279" alt="Screen Shot 2021-04-09 at 12 04 09" src="https://user-images.githubusercontent.com/24259317/114164726-ecc66300-992b-11eb-948c-1aa1bda636b9.png">


```js
{
  "Error Code": 0,
  "Message": "Http failure response for http://51.254.157.180:5000/api/projects/6064abce9d6953f3937a2e2f/users: 0 Unknown Error",
  "Error": {
    "headers": {
      "normalizedNames": {},
      "lazyUpdate": null,
      "headers": {}
    },
    "status": 0,
    "statusText": "Unknown Error",
    "url": "http://51.254.157.180:5000/api/projects/6064abce9d6953f3937a2e2f/users",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for http://51.254.157.180:5000/api/projects/6064abce9d6953f3937a2e2f/users: 0 Unknown Error",
    "error": {
      "isTrusted": true
    }
  }
}
```

**Comment by pheim1** [comment]
Hm, also über Postman & Swagger funktioniert es. Würde mal auf ein Fehler im Frontendcode setzen.

**Comment by marlonschlosshauer** [comment]
Kann es sein das der Endpunkt das Blockiert weil ein Header (Authorization) in der Anfrage ist, den es da nicht erwartet ?

**Comment by marlonschlosshauer** [comment]
Auf ``main`` läuft alles ohne Probleme, da schicke ich nie Authorization mit. Auf ``auth-header-in-services`` schicke ich es nur in Project mit und da funktioniert es auch. Sorry falls ich das unklar beschrieben habe.

**Comment by pheim1** [comment]
Nein, ich glaube eher dass die Anfrage erst gar nicht zum Backend kommt. Sonst würde es ja über Postman oder Swagger (Same origin) nicht funktionieren. Zumal der ProjectUser Controller nicht fürs Auth registriert ist, im also egal ist was im Header steht.

**Comment by pheim1** [comment]
![image](https://user-images.githubusercontent.com/58334704/114166896-973f8580-992e-11eb-9525-2db9e1275760.png)

**Comment by marlonschlosshauer** [comment]
Hm. Die nicht-rausgehen-Theorie könnte sein. Es kommt kein 404 oder 500 zurück sondern "Blocked". 
Wieso würde er nicht rausgehen ?

**Comment by marlonschlosshauer** [comment]
@BenjaminKuerten Philipp und ich sind gestern über einen komischen Bug gestolpert. Wenn wir den Authorization Header setzen funktioniert der Project Endpunkt perfekt, aber wir kriegen Timeouts für die Issue und ProjectUser Endpunkte. 
Das Problem taucht nur unter Firefox (läuft unter Chrome und Safari) auf, und nur wenn wir "Authorization" im Header mit senden. Hast du da eine Vermutung ?

**Comment by BenjaminKuerten** [comment]
@marlonschlosshauer Ich hatte schonmal ähnliche Probleme mit Firefox, ich weiß aber nicht mehr ganz wie ich diese behoben haben. Ich werde mir das morgen nochmal anschauen.

**Comment by BenjaminKuerten** [comment]
Ich habe jetzt mal einiges ausprobiert und getestet. Der Fehler sollte am Firefox Browser liegen, dieser hatte eine interne CORS. Diese CORS ist eine Sicherheit Funktion, die schützen soll vor einem falschen/fake Backend (soweit ich das verstanden habe). Bei Google findet man hunderte Berichte darüber, dass diese Timeouts oder 10+ Sekunden Lags erzeugt bei einem Request. Dieser "Schutz" kommt wohl nur zur Verwendung sobald ein Auth-Header gesetzt ist. Das Problem ist, dass das Backend ungeschützt ist (http) und auf einem anderen Host liegt (Server->Localhost).

Es gibt eine Einstellung : 
Einstellungen -> Datenschutz & Sicherheit -> Zertifikate anzeigen -> Server -> Ausnahme hinzufügen

Diese Einstellung sollte die CORS außer Kraft setzen, aber scheint nur mit einer Domain zu funktionieren.

**Comment by marlonschlosshauer** [comment]
Die Einstellung zu setzen wäre für mich die finale Lösung. Hab ich das richtig verstanden das das Backend auf HTTPS umstellen, dass fixen würde ? 
Weiß nicht wie viel Aufwand das ist, aber hört sich nach ner menge an.

Kannst du dir eklären wieso der Project Endpunkt funktioniert, aber Issued und ProjectUser nicht ?

**Comment by pheim1** [comment]
Benni müsste eine domaine mit valider ssl Zertifikat bereitstellen. Aber das wäre Overkill für ein HS Projekt.

Das komische ist ja, das es funktioniert wenn man den request ohne Services manuell in der App.component.ts ausführt. Sprich einfach httpClient.get(...); im konstruktor aufruft.

Cors und Firefox mal außer acht, wieso schlägt der call in einem Service Aufruf fehl, aber wenn man ihn manuell in einem component implementiert und ausführt nicht ?

**Comment by marlonschlosshauer** [comment]
Benny ist zum gleichen Entschluss gekommen und hat eine Domain gekauft, angefangen das ganze aufzusetzen und wir sollten bis Mittwoch das getestet haben. Wieso es manuell funktioniert werden wir (hoffentlich) nie rausfinden 🌚
