### ISSUE TITLE
Hinzufügen der Rollen beim User

### ISSUE THREAD

**Issue by BenjaminKuerten** [gedankenessen/goose-frontend#49]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [ ] Rollen werden hinzugefügt in User Interface 
- [ ] Rollen werden gesetzt beim einloggen

**Comment by BenjaminKuerten** [comment]
@marlonschlosshauer Wie ist dieses Issue gemeint? Sollen die einfach in den LocalStorage gesetzt werden? Wie ist "Rollen werden hinzugefügt in User Interface" gemeint?

**Comment by marlonschlosshauer** [comment]
:^)
