### ISSUE TITLE
IssueComponent - VS2 Verhalten

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#52]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T62 Auf Ticketansicht während Verhandlungsphase hat Kunde nur Zugriff zu gewissen Funktionen (siehe Ph.)
- [x] T63 Auf Ticketansicht während Verhandlungsphase hat Mitarbeiter nur Zugriff zu gewissen Funktionen (siehe Ph.)
- [x] T64 Auf Ticketansicht in "Kommunikation" wird Requirement in Textbox erstellt
- [x] T65 Auf Ticketansicht in "Kommunikation" wird Requirement in Textbox über Button kopiert
- [x] T70 Auf Ticketansicht in "Kommunikation" wenn Zusammenfassung gesendet wurde kann Ticket nicht mehr bearbeitet werden (außer Status zu Abbrechen)
- [x] T91 Auf Ticketansicht wenn in erstellten Statuse gibt es je nach Phase verschiedene Funktione (siehe Ph.)

**Comment by marlonschlosshauer** [comment]
Hey hey konntest du schon Fortschritt beim erstellen von Zusammenfassungen machen ? Ich würde gerne bis Mittwoch die Logik mit Louis in die ConversationComponent machen und dann spätestens am Mittwoch mit deinem Teil zusammenfügen.

**Comment by sfuerder** [comment]
Das erstellen von Zusammenfassungen ist nicht meine Aufgabe oder? Macht das nicht Moritz?

**Comment by marlonschlosshauer** [comment]
Sorry natürlich. Ich meinte das hinzufügen von Requirements im Drawer.

**Comment by sfuerder** [comment]
Wäre soweit, dass man das Zusammenführen kann

**Comment by marlonschlosshauer** [comment]
Von der IssueConversationComponent steht der Output auch schon. Was haltest du davon wenn wir die IssueConversationBranch in deine mergen (nachdem Louis den neuesten Stand gepushed hat) ?

**Comment by sfuerder** [comment]
Ja können wir gerne machen. Morgen hätte ich ab 17 Uhr Zeit, um das ganze zusammen zu führen

**Comment by marlonschlosshauer** [comment]
Super. Ich bin so ab 17:30 available. @WhiroWhat könntest du bis dahin die Output Logik commiten und pushen ? Kannst auch gerne dazu kommen falls du Zeit hast.

**Comment by WhiroWhat** [comment]
Hab die Output Logik gepushed

**Comment by marlonschlosshauer** [comment]
@sfuerder Meinst du ein PR wäre bis Mittwoch Abend oder Donnerstag Mittag machbar, oder ist es noch viel Arbeit?

**Comment by sfuerder** [comment]
Sollte machbar sein.
Noch 
1. Zu T70. Wie kann ich das Prüfen? Mache ich einfach einen Request an Summary und schaue ob ein 400 Fehler kommt?
2. Zu T91 da wäre ich soweit fertig. Solche Dinge wie Zusammenfassung schicken, Vorgänger hinzufügen, entfernen oder Zeitebuchung muss ich nicht machen bzw noch nicht machen oder?

**Comment by marlonschlosshauer** [comment]
>     1. Zu T70. Wie kann ich das Prüfen? Mache ich einfach einen Request an Summary und schaue ob ein 400 Fehler kommt?
> 

Laut Swagger gibt es das ``requirementsSummaryCreated``, das könnte dafür funktionieren.

![image](https://user-images.githubusercontent.com/24259317/116236699-ab251d00-a75f-11eb-99f0-62d3482867b8.png)




>     2. Zu T91 da wäre ich soweit fertig. Solche Dinge wie Zusammenfassung schicken, Vorgänger hinzufügen, entfernen oder Zeitebuchung muss ich nicht machen bzw noch nicht machen oder?

Genau, die musst du noch nicht machen 👍
