### ISSUE TITLE
Conversation - VS2 Verhalten, Requirements, andere Kommunikationstypen (Status etc.)

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#53]
Aufgaben:
- [x] T29 Auf Ticketansicht ist Nachrichtenfeld und Senden Button inaktiv falls Ticket archiviert ist
- [x] T56 Auf Ticketansicht unter "Kommunikation" beinhaltet Kommunikationsverlauf mehrere Typen (siehe Ph.)
- [x] T64 Auf Ticketansicht in "Kommunikation" wird Requirement in Textbox erstellt
- [x] T68 Auf Ticketansicht in "Kommunikation" kann Zusammenfassung akzeptieren/ablehnen werden
- [ ] T69 Auf Ticketansicht in "Kommunikation" kann nur der Autor oder Projektleiter die Zusammenfassung akzeptieren/ablehnen

Links: [Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804), [Zeplin](https://zpl.io/a7XKm3v)

**Comment by WhiroWhat** [comment]
@marlonschlosshauer 
T29: Wird der Archiviert-Status über den die Variable visibility von Issue gespeichert oder woher bekomme ich die?
T64: Wie ist das gemeint? 
![image](https://user-images.githubusercontent.com/48799541/114618449-a5ccca80-9ca9-11eb-9a6a-0df211375582.png)
Einfach dort noch eine TextBox hin? Wo würden die dann angezeigt werden?

**Comment by WhiroWhat** [comment]
https://docs.google.com/document/d/1sEfx8s7TNK57mixii6nnmde-BA_Cg0rQ6gjhfIwLcpw/edit# F21

**Comment by marlonschlosshauer** [comment]
> T29: Wird der Archiviert-Status über den die Variable visibility von Issue gespeichert oder woher bekomme ich die?

Im Issue sollte es "state" geben, da steht es drin. Phil kann dir da weiterhelfen wenn du Fragen zu den Daten hast.

> T64: Wie ist das gemeint?

Das ist die Vor-Version von T65. Mitarbeiter sollen über einen Button bei (je)der Nachricht (der Stern im Zeplin Mockup) den Text in den [Requirements Drawer](https://zpl.io/a8XBBJw) übertragen können. Den Drawer macht Sebastian. Deine Aufgabe ist es den Button zu impl. und Sebastian über einen Output den Text (und Nachrichten Id vielleicht) zu übergeben. Melde dich am besten bei ihm.

**Comment by WhiroWhat** [comment]
T56: Was soll da genau gemacht werden bzw. wie unterscheiden sich denn die Typen in der Darstellung?
Heißt das einfach in dem Kommunikationsverlauf steht eine Nachricht mit z. B. "Statuswechsel von bsp1 zu bsp2"?

**Comment by marlonschlosshauer** [comment]
**Nachrichten**

Wie gewohnt. 

**Statuswechsel**
**Unterticket hinzugefügt/entfernt**
**Vorgänger hinzugefügt/entfernt**


Würde ich wie die Meldungen auf Github machen. Text mit Name und Aktion in fett.
![image](https://user-images.githubusercontent.com/24259317/115119800-83d58f80-9faa-11eb-8370-af345b287589.png)


**Zusammenfassungen**

Stell ich mir sowas vor:
![Zusammenfassung](https://user-images.githubusercontent.com/24259317/115120297-16772e00-9fad-11eb-8103-fc86c9acca50.png)

**Comment by marlonschlosshauer** [comment]
Hey hey ich würde gerne vor Mittwoch noch die Logik hinzufügen das wir Nachrichten als Requirement auswählen können (Text in Drawer kopieren)

Über den Stern Button hier:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/24259317/115212601-fa84a100-a100-11eb-8d59-63d78a66b2d7.png">

Dafür bräuchten wir einen Output in der ConversationComponent. Hast du das schon mal gemacht ?

**Comment by WhiroWhat** [comment]
Ne sowas hab ich noch nicht gemacht.

**Comment by marlonschlosshauer** [comment]
Hättest du morgen eine halbe Stunde das wir schnell drüber gehen könnten ?

**Comment by WhiroWhat** [comment]
jo

**Comment by WhiroWhat** [comment]
@sfuerder kannst du IssueComponentVS2 pushen? Würde das gerne bei mir reinmergen.
