### ISSUE TITLE
Live Build von main Branch

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#54]
@pheim1 Wie viel Arbeit wäre ein deploy von der main Branch online zu stellen ? Hätte das gerne um immer ein Bild von dem momentanen Stand (und dessen Funktionsfähigkeit) zu haben.

**Comment by pheim1** [comment]
Die Infrastruktur Serverseitig steht schon, hab ich gleich schon vorbereitet, als ich es für das backend erstellt habe. Ich muss nur noch eine GitHub action erstellen und dann wird bei jedem Push auf den Main ein neues frontend deployed (außer du willst es wie im backend, dass du ein manuelles release in GitHub erstellen musst => mehr Kontrolle bei ausversehenen pushes usw)

**Comment by marlonschlosshauer** [comment]
Ein automatischer deploy hört sich gut an. Kontrolle über die Version von Backend finde ich gut, weil das Backend die Frontend Entwickler beeinflusst. 
Greenlight für die Github Action 👍
