### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by pheim1** [gedankenessen/goose-frontend#55]
**Beschreibung des Bugs**
Mir ist aufgefallen, dass im kompletten Frontend die Subscriptions nicht unsubscribed werden. Das wird Memory-Leaks produzieren und zu unerwartetem verhalten führen (mehrfach Ausführung, uvm.), wenn die subscriptions nicht entfernt werden. Um dem entgegen zu wirken, kann man Packages wie Subsink oder einen eigenen Subscription-Wrapper verwenden, den ich hier am Ende Anhänge.

**Nutzung**
Um den unten aufgeführten SubscriptionWrapper zu nutzen muss man einfach die Componenten-Klasse von dieser Erben lassen -> `class MyComponent extends SubscriptionWrapper` und in dessen Konstruktor `super()` aufrufen. 

Dann kann man ihn ganz einfach in der Componente nutzen:

```ts
// alte Vorgehensweise (Observer wird nie benachrichtigt und es entstehen memory leak):
this.service.method().subscribe( (obsOrNext) => {}, (error) => {}, (complete) => {} );

// neue Vorgehensweise (Bei der Zerstörung der Componente wird ein Unsubscribe aufgerufen um sich von dem Observer abzumelden):
this.subscribe(this.service.method(), (obsOrNext) => {}, (error) => {}, (complete) => {} );
```

Wird die Komponente am Ende ihrer Lifetime zerstört, wird natürlich die OnDestroy (deconstruktor) Methode aufgerufen und dadurch alle Subscriptions aufgelöst. Somit wissen die Observables, dass sie nicht mehr an die ghost subscriber emitten müssen. 

**Branches**
- alle

**Subscription Wrapper**
```ts
import { Directive, OnDestroy } from '@angular/core';
import { Observable, PartialObserver, Subscription } from 'rxjs';

/**
 * This is a wrapper for your component, in which you can call *this.subscribe(...)*, in order to let the base class handle the sinking. **Make sure to call super() in the constructor of the inherit class.**
 */
@Directive()
export abstract class SubscriptionWrapper implements OnDestroy {

    private subSink = new Subscription();

    /**
     * Use this function to register your subscription to the list of subscriptions which then automatically will be sinked.
     */
    protected subscribe<T>(
        observable: Observable<T>,
        observerOrNext?: PartialObserver<T> | ((value: T) => void),
        error?: (error: any) => void,
        complete?: () => void
    ): Subscription {
        return this.subSink.add(
            observable.subscribe(observerOrNext as any, error, complete)
        );
    }

    /**
     * Unsubscribe a subscription of the list of subscriptions. This will not sink the subscription on **ngOnDestroy()**
     * @param innerSub The subscription which will be removed from the list.
     */
    protected unsubscribe(innerSub: Subscription)
    {
        this.subSink.remove(innerSub)
    }

    ngOnDestroy(): void {
        this.subSink.unsubscribe();
    }

}
```

**Comment by marlonschlosshauer** [comment]
@gedankenessen/frontend

**Comment by marlonschlosshauer** [comment]
Meines Wissens nach ist das nur ein Problem bei den subscriptions auf UI Elemente. Der HTTPClient [beendet](https://stackoverflow.com/a/35043309/11062314) die Subscription nachdem die Antwort vom Server eintrifft.

**Comment by pheim1** [comment]
Da hast du zwar recht, aber wir müssen auch solche Fälle beachten, in dem der User die Componente wechselst, und der request nicht nicht erfolgreich zurück kam, dann nämlich wird nicht automatisch unsubscribed.

Unterm strich ist es sinnvoller und sauberer alle eventualiäten auszuschließen und das kann man, indem man explizit unsubscribed, sollte als best practice in den code guide, falls man einen hat.

Man ist durch den Einsatz von dem unsubscribe ja nicht negativ beeinflusst.

**Comment by marlonschlosshauer** [comment]
True. Vor allem auf dem ProjektDashboard würden (momentan) da viele Requests auf der Strecke bleiben.
