### ISSUE TITLE
IssueDashboardComponent

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#6]
- [x] Tabellenansicht
- [x] Interface
- [x] Services (Kommunikation mit Backend)

**Comment by marlonschlosshauer** [comment]
Hättest du mir ein Update wie viel du noch machen würdest ? Hab das gerade so geplant das #10 und #4 auf dieses Issue warten. Wir mergen dieses in main, danach #10 und #4, dann ein fix für die app-routing-module.

**Comment by mschwer1** [comment]
Ich würde noch die restlichen Spalten hinzufügen, das wäre erstmal alles.

**Comment by marlonschlosshauer** [comment]
Kannst machen. Deadline für das ganze, verwendbar auf der main branch, ist Mittwoch. Denk dran das der Issue Service sich sehr sehr ändern wird (mehr dazu in #2).
