### ISSUE TITLE
Registrieren Error wenn kein Token gesetzt

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-frontend#60]
**Beschreibung des Bugs**
Wenn man sich registrieren möchte und kein Token im Local Storage gesetzt ist,
bekommt man den folgenden Error: (Unter Chrome)
![grafik](https://user-images.githubusercontent.com/48796374/114559983-8d8a8a80-9c6c-11eb-83a4-f5933909619a.png)

**Reproduktions Schritte**
1. F12 drücken
2. In den Tab 'Application' wechseln
3. Im LocalStorage den Token clearen
4. Auf localhost:4200/register auf Registrieren drücken

**Erwartetes Verhalten**
Das registrieren erfolgt auch ohne gesetzten Token problemlos

**Branches**
- Frontend: main
- Backend: live

**Comment by marlonschlosshauer** [comment]
@BenjaminKuerten Müsste noch nen Check im Interceptor rein, ob schon der Token im Localstorage ist, oder ?

**Comment by BenjaminKuerten** [comment]
Nein, der Interceptor kopiert nur immer wieder den Token mit. 
Ich habe nur zwei Vermutungen:
1. Die "loginAfterRegister" Methode im Auth-Service setzt den Token nicht richtig bzw. Felder werden nicht richtig gesetzt
2. Des wird zuerst der Seitenwechsel ausgeführt und dann erst die "loginAfterRegister" Methode aufgerufen (Delay vom Request), somit versucht er einen nicht existierenden Token zu kopieren

**Comment by marlonschlosshauer** [comment]
>     2\. Es wird zuerst der Seitenwechsel ausgeführt und dann erst die "loginAfterRegister" Methode aufgerufen (Delay vom Request), somit versucht er einen nicht existierenden Token zu kopieren

Da leg ich mein Geld drauf 💰

**Comment by Namo2** [comment]
Schaue es mir gleich mal an

**Comment by Namo2** [comment]
So wie ich das jetzt verstanden habe hängt der Interceptor an jeden Request den Auth-Header an.
Das ganze passiert dadurch, dass er aus dem AuthService die currentUserValue abfragt.
Allerding ist vor dem login diese Variable natürlich null => deswegen 'Cannot read property ... of null'

Ein einfacher fix wäre wohl ein null check mit dem ? operator:
`
intercept(request: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
    return next.handle(request.clone({ setHeaders: { Authorization: `Bearer ${this.authService.currentUserValue?.token}` } }));
}
`

Bei den Tests die ich gemacht habe klappt alles.
Bin mir aber nicht sicher ob dadurch nicht doch etwas kaputt gehen könnte.
@marlonschlosshauer @BenjaminKuerten

**Comment by marlonschlosshauer** [comment]
Das wäre eine Lösung. Die elegante Lösung wäre keinen Header anzuhängen wenn wir wissen das currentUserToken null ist. @BenjaminKuerten kann man hier einfach ``return next`` machen wenn man keine Kopie des Requests machen möchte ?

**Comment by Namo2** [comment]
@BenjaminKuerten haben jetzt dafür eine Branch (hotfix/RegisterTokenError) falls dir noch etwas einfällt

**Comment by BenjaminKuerten** [comment]
@Namo2 Ich würde eher wie @marlonschlosshauer sagt, dass gar kein Header anhängen wird sobald dieser null ist. Mit dem return next sollte eigentlich funktionieren.

**Comment by marlonschlosshauer** [comment]
@Namo2 wenn du möchtest kannst du das gerne mal erforschen und einen hotfix machen.

**Comment by marlonschlosshauer** [comment]
Habs gefixed. Ging mir zu sehr auf die nerven 😂

**Comment by Namo2** [comment]
> Habs gefixed. Ging mir zu sehr auf die nerven joy

Haha wollte mich gerade dran setzen und jetzt ein Kommentar schreiben, dass in main bereits eine Version ist die für uns passt 
😂
