### ISSUE TITLE
Dynamische anpassung von Komponenten je nach Zugriffsrechten

### ISSUE THREAD

**Issue by Namo2** [gedankenessen/goose-frontend#68]
[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T16 Nur Firma sieht Projekt erstellen Button
- [x] T59 Auf Ticketansicht unter "Zugewiesen" können Mitarbeiter nur von Projektleiter hinzugefügt/entfernt werden
- [x] T84 Nur Mitarbeiter mit Schreibrecht, Firma und Projektleiter können Projekteinstellugen aufrufen
- [x] T18 Nur Firma sieht Mitarbeiter erstellen Button
- [x] T17 Nur Firma sieht Kunden erstellen Button

**Comment by Namo2** [comment]
@marlonschlosshauer habe hier mal aufgeschrieben um was ich mich erstmal kümmern würde.
Ich denke nicht, dass das all zu lange dauern wird. Ich schaue mal was ich danach noch machen könnte.
T17 + T18 würde meiner Meinung nach auch noch dazu gehören.
Glaube aber solche Buttons existieren noch garnicht oder? :D

**Comment by marlonschlosshauer** [comment]
Das Problem ist das diese Sachen in Dateien passieren die andere schon bearbeiten. z.B. musst du bei T59 warten bis Moritz fertig ist.

T84 beinhaltet den Projektleiter, was eigentlich P2 ist. Kannst du von mir aus aber gerne machen.

T16, T17 und T18 finde ich passen gut.

Mein einziges Problem ist mit dem kollidieren, wenn zwei gleichzeitig an einer Datei arbeiten.

**Comment by marlonschlosshauer** [comment]
Wenn ich das richtig verstehe würdest du also mit einem AP all diese Komponenten anfassen:



<table>


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<tbody>
<tr>
<td class="org-left">T16</td>
<td class="org-left">ProjectDashboard</td>
<td class="org-left">Frei</td>
</tr>


<tr>
<td class="org-left">T17</td>
<td class="org-left">CustomerDashboard</td>
<td class="org-left">Lukas</td>
</tr>


<tr>
<td class="org-left">T18</td>
<td class="org-left">EmployeeDashboard</td>
<td class="org-left">Frei</td>
</tr>


<tr>
<td class="org-left">T59</td>
<td class="org-left">IssueAssigned</td>
<td class="org-left">Moritz</td>
</tr>


<tr>
<td class="org-left">T84</td>
<td class="org-left">ProjectSettings</td>
<td class="org-left">Frei</td>
</tr>
</tbody>
</table>

Lukas würde erst jetzt mit seinem Paket anfangen, Moritz ist bis morgen fertig. Ich glaube es wäre aber Wert voll ihn weiter an seinem Code arbeiten zu lassen (außer Pair Programming wäre möglich).

**Comment by Namo2** [comment]
Stimmt da hast du recht. Deswegen frage ich dich :D
Hab ja keinen Überblick wer wo gerade dran arbeitet.

Na gut dann würde ich mich an die Komponenten dransetzen welche Frei sind.

Andere Frage. Bei T84, würde ich das dann wirklich in den ProjektSeetings einbauen oder würde das nicht auch auf dem ProjektDashboard sein (also das der Button zu den Settings nicht angezeigt wird)

**Comment by marlonschlosshauer** [comment]
Yo mach das 👍 

Bei T84 kannst du den redirect machen, aber aufjedenfall auch den Button ausblenden.

**Comment by Namo2** [comment]
@Luk-T @marlonschlosshauer hab bemerkt, dass das Customer Dashboard noch keinen "Kunden Erstellen" Button hat.
Sollte ich den auch noch hinzufügen, wenn ich mich um T17 kümmere?

**Comment by marlonschlosshauer** [comment]
Gerne 👍

**Comment by Namo2** [comment]
Wer kann denn alles einen Kunden bearbeiten?
Dann würde ich die Rechte für die QuickActions auch kurz machen
