### ISSUE TITLE
IssueDashboard: Anzeige + Sort&Filter

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#83]
Ziel wäre für mich das das Ticketdashboard komplett ist. Dann ab nächsten Mittwoch würde ich dir das "Card Design" Dashboard geben.

Ich setze KW17 (3. Mai) als Milestone, für mich ist die Deadline auf Mittwoch (5. Mai). Passt das Zeitlich?

[Tracebility](https://docs.google.com/spreadsheets/d/1fkJJCobvPiYgjcRDpPSxfUmstBT5icVhqKs293oSzsQ/edit#gid=341667804): 

- [x] T38 Auf Ticketdashboard sieht ein lesender Mitarbeiter den Ticket erstellen Button nicht
- [x] T46 Auf Ticketdashboard wird "Ampel" angezeigt (siehe Ph.)
- [x] T95 Auf Ticketdashboard kann gefiltered werden (siehe Ph.)
- [x] T96 Auf Ticketdashboard kann soritert werden (siehe Ph.)

**Comment by marlonschlosshauer** [comment]
@sfuerder Wenn wir das Card-Design machen, wäre das natürlich eine neue Komponente. Siehst du hier die Möglichkeit Funktionalität zu teilen (mit dem normalen Dashboard) oder haltest du das für Zeitverschwendung?

**Comment by sfuerder** [comment]
Ich würde schauen, dass ich von vorne rein Komponenten, die in beiden Dashboards vorkommen evtl als eigene Komponenten mache und diese dann einfach wiederverwenden kann.

**Comment by sfuerder** [comment]
5. Mai scheint mir unmöglich zu sein 😅
Du meintest wohl eher den 12. Mai oder?

**Comment by marlonschlosshauer** [comment]
>  Du meintest wohl eher den 12. Mai oder?

Yo 😅 Würde die Deadline ggf. auch auf Freitag erhöhen.

@sfuerder @mschwer1 Könnt ihr beiden euch zusammen tun und drüber reden wie und was ihr teilen würdet. Ich würde dir Sebastian dann das Card-Design Dashboard geben, wo du parallel dran arbeiten kannst.

**Comment by sfuerder** [comment]
Sollte möglich sein 👍🏻

**Comment by sfuerder** [comment]
@mschwer1 Ich würde den Fortschrittsbalken und evtl die Priorität als eigene Komponente entwickeln, so dass in der Tabellen Ansicht, sowie in der Card Ansicht die Komponenten eingebunden werden können

**Comment by sfuerder** [comment]
@mschwer1 Ich habe eine Branch IssueCardDesign angelegt. Dort habe ich alle Vorbereitungen getroffen, um die Komponenten zu erstellen. Am besten machst du von dort eine neue Branch auf, damit du dort dann das Ticket Dashboard weiter entwickeln kannst.

**Comment by mschwer1** [comment]
@sfuerder Mache ich. Ich hatte letztes Wochenende schonmal mit den verschiedenen Sachen angenfangen, und so wie ich es momentan verstehe, ist die Progress Bar an sich ja schon eine einzige Komponente, die man in die Tabelle einsetzen kann. Ist es da nötig, nochmal eine zusätzliche Komponente zu erstellen?

**Comment by sfuerder** [comment]
Ich hätte schon gesagt, dass es hier Sinn macht, da diese Komponente ja auch in dem Card Design benötigt wird und die Fortschrittsanzeige auch noch die kleine Funktion mit den Farben hat. Ich bin generell ein Freund davon so wenig wie möglich Programmcode doppelt zu haben. @marlonschlosshauer was meins du dazu?

**Comment by marlonschlosshauer** [comment]
Ups sorry hab das am Ende überlesen. Klar, liebe das wiederverwenden von Code. Nicht nur schreiben wir weniger, sondern der zu wieder-verwendende Code wird besser geschrieben.

**Comment by marlonschlosshauer** [comment]
Hey hey, wie sieht hier der Fortschritt aus?

**Comment by mschwer1** [comment]
Alle Anforderungen funktionieren jetzt, ich würde dann eine Pull Request erstellen.
