### ISSUE TITLE
IssueSettings werden nicht alle Statuse angezeigt

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#91]
**Beschreibung des Bugs**
IssueSettings bietet nur zwei Statuse zur auswahl (Überprüfen, Bearbeiten). 
Wenn das Ticket aber schon erstellt ist sollten da mehr auftauchen oder wenn z.B. eine Zusammenfassung angenommene wurde, wird gar kein Status mehr angezeigt (und bietet nur standard zur Auswahl).
![image](https://user-images.githubusercontent.com/24259317/116712264-f6dffc80-a9d3-11eb-8847-59f571172d4c.png)

**Reproduktions Schritte**
1. Ticket erstellen
2. Ticket bearbeiten
3. Ticket Status öffnen

**Branches**
- Frontend: **demo (IssueSettings wurde reingemerged)**
- Backend: master

**Comment by BenjaminKuerten** [comment]
Sämtliche Bugs werden heute behoben
