### ISSUE TITLE
Auf Ticketansicht "Bearbeiten" Button immer anzeigen

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#92]
Hab gerade gesehen das es einen ["Abbrechen" Button](https://user-images.githubusercontent.com/24259317/116713151-cea4cd80-a9d4-11eb-9242-d2e18eae29e4.png) gibt, wenn die Bearbeiten Phase erreicht ist. Ich würde den Bearbeiten Button weiterhin anzeigen (für alle außer lesende Mitarbeiter und Kunde wenn er kein Autor ist). 

Falls du vor dem Meeting ändern möchtest, **branche von der Branch demo**.

**Comment by marlonschlosshauer** [comment]
Wurde gefixed, oder? @sfuerder

**Comment by sfuerder** [comment]
Jop
