### ISSUE TITLE
"isAuthorized", "isCompany" etc. in Service verallgemeinern?

### ISSUE THREAD

**Issue by marlonschlosshauer** [gedankenessen/goose-frontend#93]
Mir ist aufgefallen das wir oft in den Componenten die gleichen Abfragen zu den Rollen machen. Es würde Sinn machen das wir einen zentralen Service dafür erstellen, der einem die Rollen und rechte wiedergibt. 

Irgendwelche Ideen für die Implementierung?

**Comment by pheim1** [comment]
Falls ich dich richtig verstanden habe (bitte korrigier mich): Ich würde für das einblenden oder ausblenden von Elementen zwei direktiven schreiben, welches man eine Rolle(enum der Rollen Namen) mitgeben kann. Die direktive kann ja auf einen auth Service zugreifen und daraufhin die Rollen des eingeloggten Users in entweder company(companyRoleDirective) oder Project (projectRoleDirective) überprüfen.

**Comment by marlonschlosshauer** [comment]
>  Ich würde für das einblenden oder ausblenden von Elementen zwei direktiven schreiben

Finde ich eine verdammt gute Idee.

**Comment by Luk-T** [comment]
> @Luk-T Ich hab gesehen das du die Rollen als Konstante hinzugefügt hast. Das ist super. Könnten wir da auch ein Enum draus machen ?

Natürlich, da hab ich irgendwie gar nicht daran gedacht
